#------------------------------------------------------------------------------
# CF_Take_scripts.R
#
# This file contains functions to recreate results for the Take chloroform 
# experiments modeled by Sasso et. al. (2013).
#
# Author: Bidya Prasad, December 2021
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

library(readxl)

# Load functions to run the PBPK model template.
source("run_template_model.R")

# Compile the model. (You only need to do this once.)
#compile_model("PBPK_template")

# Load the model.
#load_model("PBPK_template")

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#2A788EFF", "#7AD151FF") # viridis(3, begin = 0.0, end = 0.8)
pub.col <- vcol[2]
templ.col <- vcol[3]
pub.lty <- "dashed"
templ.lty <- "solid"
paper.col <- vcol[2]
paper.lty <- "dashed"

chloroform.Take.oral <- function(){
  # Creates manuscript Figure S-5
  
  TSTOP = 600         # Simulation time (min).
  CINT = 0.1          # Frequency with which solver should report results (min).
  times = seq(from=0, to=TSTOP, by=CINT)
  
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet = "oral")
  take_acslx_oral_output <- read_excel("Data/Data_CF/Take_acslx_output.xlsx", 
                                       sheet = "oral")
  
  # Simulates male rats exposed to an oral dose of chloroform
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_oral",
                  data.times = times)
  
  # Time in minutes
  time_min <- out[,"time"]*60
  time_min1 <- time_min[10:5500]
  
  # Generate a figure that shows blood concentrations vs. time.
  C_ven_out <- out[,"C_ven"]
  C_ven_out1 <- C_ven_out[10:5500]
  
  df_C_ven = data.frame(time_min, C_ven_out)
  
  is.na(df_C_ven[df_C_ven==0]) <- TRUE
  
  bl_min = data.frame(Time=c(take_data[,1]),
                      Conc=c(take_data[,2]))
  bl_data = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,3]))
  bl_max = data.frame(Time=c(take_data[,1]),
                      Conc=c(take_data[,4]))
  
  bl_acslx_model = data.frame(time_acslx_mod=c(take_acslx_oral_output[,1]),
                              ven_bl_acslx_mod=c(take_acslx_oral_output[,2]))
  
  par(mfrow = c(2, 2), mar = c(5, 5, 0, 0), oma = c(3, 0, 1, 2))
  
  plot(time_min1, C_ven_out1, type="l", lwd=4, lty=templ.lty, cex = 0.2, col=templ.col, 
       log="y", cex.main = 0.8, xlab="Time (min)",  
       ylab="Blood Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(bl_min$time[1:7], bl_min$blood_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(bl_data$time[1:7], bl_data$blood_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(bl_max$time[1:7], bl_max$blood_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(bl_acslx_model$time, bl_acslx_model$blood_conc, 
        lwd=4, cex = 0.2, lty=pub.lty,
        col=pub.col)
  
  # Generate a figure that shows fat concentrations vs. time.
  fat_out <- out[,"C_tc3"] * 0.9
  fat_out1 <- fat_out[10:5500]
  is.na(fat_out[fat_out==0]) <- TRUE
  
  fat_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,5]))
  fat_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,6]))
  fat_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,7]))
  
  fat_acslx_model = data.frame(time_acslx_mod=c(take_acslx_oral_output[,1]),
                               fat_acslx_mod=c(take_acslx_oral_output[,3]))
  
  #par(mar=c(3.3, 3.1, 2.2, 1.1), mgp = c(2, 0.5, 0))
  plot(time_min1, fat_out1, type="l", lwd=4, lty=1, col=templ.col, log="y",
       cex.main = 0.8, xlab="Time (min)",  
       ylab="Fat Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(fat_data$time[1:7], fat_data$fat_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(fat_max$time[1:7], fat_max$fat_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(fat_min$time[1:7], fat_min$fat_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(fat_acslx_model$time, fat_acslx_model$fat_conc, lwd=4, cex = 0.2, lty=pub.lty,
        col=pub.col)
  
  # Generate a figure that shows kidney concentrations vs. time.
  kid_out <- (out[,"A_ki"] + out[,"A_om"]) / (out[,"V_ki"] + out[,"V_om"])
  kid_out1 <- kid_out[10:5500]
  is.na(kid_out[kid_out==0]) <- TRUE
  
  kid_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,8]))
  kid_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,9]))
  kid_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,10]))
  
  kid_acslx_model = data.frame(time_acslx_mod=c(take_acslx_oral_output[,1]),
                               kid_acslx_mod=c(take_acslx_oral_output[,4]))
  
  #par(mar=c(3.3, 3.1, 2.2, 1.1), mgp = c(2, 0.5, 0))
  plot(time_min1, kid_out1, type="l", lwd=4, lty=1, col=templ.col, log="y",
       cex.main = 0.8, xlab="Time (min)",  
       ylab="Kidney Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(kid_min$time[1:7], kid_min$kidney_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(kid_data$time[1:7], kid_data$kidney_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(kid_max$time[1:7], kid_max$kidney_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(kid_acslx_model$time, kid_acslx_model$kidney_conc, lwd=4, cex = 0.2, lty=pub.lty,
        col=pub.col)
  
  #Generate a figure that shows liver concentrations vs. time.
  liv_out <- out[,"C_li"]
  liv_out1 <- liv_out[10:5500]
  is.na(liv_out[liv_out==0]) <- TRUE
  
  liv_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,11]))
  liv_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,12]))
  liv_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,13]))
  
  liv_acslx_model = data.frame(time_acslx_mod=c(take_acslx_oral_output[,1]),
                               liv_acslx_mod=c(take_acslx_oral_output[,5]))
  
  #par(mar=c(3.3, 3.1, 2.2, 1.1), mgp = c(2, 0.5, 0))
  plot(time_min1, liv_out1, type="l", 
       lwd=4, lty=templ.lty, cex = 0.2, col=templ.col, 
       log="y", 
       cex.main = 0.8, xlab="Time (min)",  
       ylab="Liver Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(liv_min$time[1:7], liv_min$liver_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(liv_data$time[1:7], liv_data$liver_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(liv_max$time[1:7], liv_max$liver_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(liv_acslx_model$time, liv_acslx_model$liver_conc, lwd=4, cex = 0.2, lty=pub.lty,
        col=pub.col)
  
  par(mfrow = c(1,1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
  plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
  
  legend("bottomleft", c("Median Data", "Min/Max Data"),
         xpd = TRUE, inset = c(0.15, -0.01), bty = "n",
         col = c(pub.col, pub.col),
         lty = c(NA,NA),
         pch = c(19,8), lwd = c(1,2), cex=1.12)

  legend("bottomleft", c("Sasso et al. (2013) Model", "Template Version"),
         xpd = TRUE, inset = c(0.57, -0.01), bty = "n",
         col = c(pub.col, templ.col),
         lty = c(pub.lty, templ.lty),
         pch = c(NA,NA), lwd = c(2,3), cex=1.12)
}

plot.CF.Take.oral <- function(){
  svg(filename="plot.CF.Take.oral.svg", 
      width=12, 
      height=9,
      pointsize=12)
  chloroform.Take.oral()
  dev.off()  
}

chloroform.Take.inhalation <- function(){
  # Creates manuscript Figure S-6
  
  TSTOP = 600         # Simulation time (min).
  CINT = 0.1          # Frequency with which solver should report results (min).
  times = seq(from=0, to=TSTOP, by=CINT)
  
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet = "inhalation")
  take_acslx_output <- read_excel("Data/Data_CF/Take_acslx_output.xlsx", 
                                  sheet = "inhalation")
  
  # Simulates male rats exposed to an inhaled dose of chloroform
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_inhalation",
                  data.times = times)
  
  # Time in minutes
  time_min <- out[,"time"]*60
  time_min1 <- time_min[5:4810] 
  # the time_min1 vector truncates the template plot so that it matches up with
  # the acslx plot
  
  # Generate a figure that shows blood concentrations vs. time.
  C_ven_out <- out[,"C_ven"]
  C_ven_out1 <- C_ven_out[5:4810]
  # the C_ven_out1 vector truncates the template plot so that it matches up with
  # the acslx plot
  
  df_C_ven = data.frame(time_min, C_ven_out)
  
  is.na(df_C_ven[df_C_ven==0]) <- TRUE
  
  bl_min = data.frame(Time=c(take_data[,1]),
                      Conc=c(take_data[,2]))
  bl_data = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,3]))
  bl_max = data.frame(Time=c(take_data[,1]),
                      Conc=c(take_data[,4]))
  
  bl_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                              ven_bl_acslx_mod=c(take_acslx_output[,2]))
  
  par(mfrow = c(2, 2), mar = c(5, 5, 0, 0), oma = c(3, 0, 1, 2))
  plot(time_min1, C_ven_out1, type="l", lwd=4, lty=templ.lty, col=templ.col, 
       log="y",  
       cex.main = 0.8, xlab="Time (min)",  ylab="Blood Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(bl_min$time[1:7], bl_min$blood_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(bl_data$time[1:7], bl_data$blood_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(bl_max$time[1:7], bl_max$blood_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(bl_acslx_model$time, bl_acslx_model$blood_conc, lwd=4,  lty=pub.lty,
        col=pub.col)
  
  # Generate a figure that shows fat concentrations vs. time.
  time_min2 <- time_min[8:4810]
  fat_out <- out[,"C_tc3"] * 0.9
  fat_out1 <- fat_out[8:4810]
  
  is.na(fat_out[fat_out==0]) <- TRUE
  
  fat_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,5]))
  fat_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,6]))
  fat_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,7]))
  
  fat_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               fat_acslx_mod=c(take_acslx_output[,3]))
  
  plot(time_min2, fat_out1, type="l", lwd=4, lty=templ.lty, col=templ.col, 
       log="y",  
       cex.main = 0.8, xlab="Time (min)",  ylab="Fat Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(fat_data$time[1:7], fat_data$fat_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(fat_max$time[1:7], fat_max$fat_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(fat_min$time[1:7], fat_min$fat_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(fat_acslx_model$time, fat_acslx_model$fat_conc, lwd=4, lty=pub.lty,
        col=pub.col)
  
  # Generate a figure that shows kidney concentrations vs. time.
  kid_out <- (out[,"A_ki"] + out[,"A_om"]) / (out[,"V_ki"] + out[,"V_om"])
  kid_out1 <- kid_out[5:4810] 
  
  is.na(kid_out[kid_out==0]) <- TRUE
  
  kid_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,8]))
  kid_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,9]))
  kid_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,10]))
  
  kid_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               kid_acslx_mod=c(take_acslx_output[,4]))
  
  plot(time_min1, kid_out1, type="l", lwd=4, lty=templ.lty,
       col=templ.col, log="y",
       cex.main = 0.8, xlab="Time (min)",  ylab="Kidney Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(kid_min$time[1:7], kid_min$kidney_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(kid_data$time[1:7], kid_data$kidney_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(kid_max$time[1:7], kid_max$kidney_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(kid_acslx_model$time, kid_acslx_model$kidney_conc, lwd=4, lty=pub.lty,
        col=pub.col)

  #Generate a figure that shows liver concentrations vs. time.
  liv_out <- out[,"C_li"]
  liv_out1 <- liv_out[5:4810]
  is.na(liv_out[liv_out==0]) <- TRUE
  
  liv_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,11]))
  liv_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,12]))
  liv_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,13]))
  
  liv_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               liv_acslx_mod=c(take_acslx_output[,5]))
  
  plot(time_min1, liv_out1, type="l", lwd=4, lty=templ.lty, col=templ.col, 
       log="y", 
       cex.main = 0.8, xlab="Time (min)",  ylab="Liver Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(liv_min$time[1:7], liv_min$liver_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(liv_data$time[1:7], liv_data$liver_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(liv_max$time[1:7], liv_max$liver_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(liv_acslx_model$time, liv_acslx_model$liver_conc, lwd=4, lty=pub.lty,
        col=pub.col)
  
  par(mfrow = c(1,1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
  plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
  
  legend("bottomleft", c("Median Data", "Min/Max Data"),
         xpd = TRUE, inset = c(0.15, -0.01), bty = "n",
         col = c(pub.col, pub.col),
         lty = c(NA,NA),
         pch = c(19,8), lwd = c(1,2), cex=1.12)
  
  legend("bottomleft", c("Sasso et al. (2013) Model", "Template Version"),
         xpd = TRUE, inset = c(0.57, -0.01), bty = "n",
         col = c(pub.col, templ.col),
         lty = c(pub.lty, templ.lty),
         pch = c(NA,NA), lwd = c(2,3), cex=1.12)
}

plot.CF.Take.inh <- function(){
  svg(filename="plot.CF.Take.inh.svg", 
      width=12, 
      height=9,
      pointsize=12)
  chloroform.Take.inhalation()
  dev.off()  
}

chloroform.Take.oral.and.inh <- function(){
  # Creates manuscript Figure 9
  
  TSTOP = 600         # Simulation time (min).
  CINT = 0.1          # Frequency with which solver should report results (min).
  times = seq(from=0, to=TSTOP, by=CINT)
  
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet = "oral_inhalation")
  take_acslx_output = read_excel("Data/Data_CF/Take_acslx_output.xlsx", 
                                 sheet = "oral_inhalation")
  
  # Simulates male rats exposed to an inhaled dose of chloroform
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_oral_inh",
                  data.times = times)
  
  # Time in minutes
  time_min <- out[,"time"]*60
  time_min3 <- time_min[10:5250]
  
  # Generate a figure that shows blood concentrations vs. time.
  C_ven_out <- out[,"C_ven"]
  C_ven_out3 <- C_ven_out[10:5250]
  df_C_ven = data.frame(time_min, C_ven_out)
  
  is.na(df_C_ven[df_C_ven==0]) <- TRUE
  
  bl_min = data.frame(Time=c(take_data[,1]),
                      Conc=c(take_data[,2]))
  bl_data = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,3]))
  bl_max = data.frame(Time=c(take_data[,1]),
                      Conc=c(take_data[,4]))
  
  bl_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                              ven_bl_acslx_mod=c(take_acslx_output[,2]))
  
  par(mfrow = c(2, 2), mar = c(5, 5, 0, 0), oma = c(3, 0, 1, 2))
  plot(time_min3, C_ven_out3, type="l", lwd=4, lty=templ.lty, cex = 0.2, col=templ.col, 
       log="y", 
       xlab="Time (min)",  ylab="Blood Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(bl_min$time[1:7], bl_min$blood_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(bl_data$time[1:7], bl_data$blood_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(bl_max$time[1:7], bl_max$blood_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(bl_acslx_model$time, bl_acslx_model$blood_conc, lwd=4, cex = 0.2, lty=pub.lty,
        col=pub.col)
  
  # Generate a figure that shows fat concentrations vs. time.
  fat_out <- out[,"C_tc3"] * 0.9
  time_min4 <- time_min[10:5250]
  fat_out3 <- fat_out[10:5250]
  is.na(fat_out[fat_out==0]) <- TRUE
  
  fat_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,5]))
  fat_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,6]))
  fat_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,7]))
  
  fat_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               fat_acslx_mod=c(take_acslx_output[,3]))
  
  plot(time_min4, fat_out3, type="l", lwd=4, lty=templ.lty, cex = 0.2, col=templ.col, 
       log="y", 
       cex.main = 0.8, xlab="Time (min)",  ylab="Fat Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 150.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(fat_data$time[1:7], fat_data$fat_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(fat_max$time[1:7], fat_max$fat_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(fat_min$time[1:7], fat_min$fat_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(fat_acslx_model$time, fat_acslx_model$fat_conc, lwd=4, cex = 0.2, lty=pub.lty,
        col=pub.col)
  
  # Generate a figure that shows kidney concentrations vs. time.
  kid_out <- (out[,"A_ki"] + out[,"A_om"]) / (out[,"V_ki"] + out[,"V_om"])
  kid_out1 <- kid_out[15:6025]
  is.na(kid_out[kid_out==0]) <- TRUE
  time_min5 <- time_min[15:6025]
  
  kid_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,8]))
  kid_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,9]))
  kid_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,10]))
  
  kid_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               kid_acslx_mod=c(take_acslx_output[,4]))
  
  plot(time_min5, kid_out1, type="l", lwd=4, lty=templ.lty, cex = 0.2, col=templ.col, 
       log="y", 
       cex.main = 0.8, xlab="Time (min)", 
       ylab="Kidney Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(kid_min$time[1:7], kid_min$kidney_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(kid_data$time[1:7], kid_data$kidney_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(kid_max$time[1:7], kid_max$kidney_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(kid_acslx_model$time, kid_acslx_model$kidney_conc, lwd=4, cex = 0.2, lty=pub.lty,
        col=pub.col)
  
  #Generate a figure that shows liver concentrations vs. time.
  liv_out <- out[,"C_li"]
  liv_out1 <- liv_out[15:6000]
  time_min6 <- time_min[15:6000]
  
  liv_min = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,11]))
  liv_data = data.frame(Time=c(take_data[,1]),
                        Conc=c(take_data[,12]))
  liv_max = data.frame(Time=c(take_data[,1]),
                       Conc=c(take_data[,13]))
  
  liv_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               liv_acslx_mod=c(take_acslx_output[,5]))
  
  plot(time_min6, liv_out1, type="l", lwd=4, lty=templ.lty, cex = 0.2, col=templ.col, 
       log="y", 
       cex.main = 0.8, xlab="Time (min)",  ylab="Liver Concentration (mg/L)",
       xlim=c(0, 500), ylim=c(0.005, 100.0), cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  points(liv_min$time[1:7], liv_min$liver_min[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  points(liv_data$time[1:7], liv_data$liver_data[1:7], type="p", pch=19,
         cex=1.5, col=pub.col)
  points(liv_max$time[1:7], liv_max$liver_max[1:7], type="p", pch=8,
         cex=1.5, col=pub.col)
  lines(liv_acslx_model$time, liv_acslx_model$liver_conc, lwd=4, cex = 0.2, lty=pub.lty,
        col=pub.col)
  
  par(mfrow = c(1,1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
  plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
  
  legend("bottomleft", c("Median Data", "Min/Max Data"),
         xpd = TRUE, inset = c(0.15, -0.01), bty = "n",
         col = c(pub.col, pub.col),
         lty = c(NA,NA),
         pch = c(19,8), lwd = c(1,2), cex=1.12)
  
  legend("bottomleft", c("Sasso et al. (2013) Model", "Template Version"),
         xpd = TRUE, inset = c(0.57, -0.01), bty = "n",
         col = c(pub.col, templ.col),
         lty = c(pub.lty, templ.lty),
         pch = c(NA,NA), lwd = c(2,3), cex=1.12)
}

plot.CF.Take.oral.inh <- function(){
  svg(filename="plot.CF.Take.oral.inh.svg", 
      width=12, 
      height=9, 
      pointsize=12)
  chloroform.Take.oral.and.inh()
  dev.off()  
}

chloroform.Take.oral.percent.diffs <- function(){
  # Calculate error: percent difference between template and acslx models
  # Discard first data point at time = 0, C_ven = 0
  
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet = "oral")
  take_acslx_oral_output = read_excel("Data/Data_CF/Take_acslx_output.xlsx", sheet = "oral")
  
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx", 
                  model.param.sheetname = "Revised_rat_params", 
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_oral")
  
  # Time in minutes
  time_min <- out[,"time"]*60
  time <- time_min
  
  ntimes_acslx = length(take_acslx_oral_output[["time"]])
  ntimes_template = length(out[,"time"])
  
  C_ven_out <- out[,"C_ven"]
  fat_out <- out[,"C_tc3"] * 0.9
  kid_out <- (out[,"A_ki"] + out[,"A_om"]) / (out[,"V_ki"] + out[,"V_om"])
  liv_out <- out[,"C_li"]
  
  print("The following values are calculated from the oral route models.")
  
  bl_acslx_model = data.frame(time_acslx_mod=c(take_acslx_oral_output[,1]),
                              ven_bl_acslx_mod=c(take_acslx_oral_output[,2]))
  bl_template_model = data.frame(time, C_ven_out)
  bl_acslx_model = bl_acslx_model[rowSums(bl_acslx_model[])>0,]
  df_acslx_temp_merge <- merge(na.omit(bl_acslx_model), 
                               na.omit(bl_template_model), by.x='time')
  err_bl_temp_acslx_oral = max(abs(perc.diff(df_acslx_temp_merge[,"C_ven_out"], 
                                             df_acslx_temp_merge[,"blood_conc"])))
  
  print("Maximum percentage difference between template and acslx models")
  print(paste0("  in blood compartment:  ", err_bl_temp_acslx_oral))
  
  fat_acslx_model = data.frame(time_acslx_mod=c(take_acslx_oral_output[,1]),
                               fat_acslx_mod=c(take_acslx_oral_output[,3]))
  fat_template_model = data.frame(time, fat_out)
  fat_acslx_model = fat_acslx_model[rowSums(fat_acslx_model[])>0,]
  fat_acslx_temp_merge <- merge(na.omit(fat_acslx_model), 
                                na.omit(fat_template_model), by.x='time')
  err_fat_temp_acslx_oral = max(abs(perc.diff(fat_acslx_temp_merge[,"fat_out"], 
                                              fat_acslx_temp_merge[,"fat_conc"])))
  
  print(paste0("  in fat compartment:    ", err_fat_temp_acslx_oral))
  
  
  kid_acslx_model = data.frame(time_acslx_mod=c(take_acslx_oral_output[,1]),
                               kid_acslx_mod=c(take_acslx_oral_output[,4]))
  kid_template_model = data.frame(time, kid_out)
  kid_acslx_model = kid_acslx_model[rowSums(kid_acslx_model[])>0,]
  kid_acslx_temp_merge <- merge(na.omit(kid_acslx_model), 
                                na.omit(kid_template_model), by.x='time')
  err_kid_temp_acslx_oral = max(abs(perc.diff(kid_acslx_temp_merge[,"kid_out"], 
                                              kid_acslx_temp_merge[,"kidney_conc"])))
  
  print(paste0("  in kidney compartment: ", err_kid_temp_acslx_oral))
  
  
  liv_acslx_model = data.frame(time_acslx_mod=c(take_acslx_oral_output[,1]),
                               liv_acslx_mod=c(take_acslx_oral_output[,5]))
  liv_template_model = data.frame(time, liv_out)
  liv_acslx_model = liv_acslx_model[rowSums(liv_acslx_model[])>0,]
  liv_acslx_temp_merge <- merge(na.omit(liv_acslx_model), 
                                na.omit(liv_template_model), by.x='time')
  
  err_liv_temp_acslx_oral = max(abs(perc.diff(liv_acslx_temp_merge[,"liv_out"], 
                                              liv_acslx_temp_merge[,"liver_conc"])))
  
  print(paste0("  in liver compartment:  ", err_liv_temp_acslx_oral))
}

chloroform.Take.inhal.percent.diffs <- function(){
  # Calculate error: percent difference between template and acslx models
  # Discard first data point at time = 0, C_ven = 0
  
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet = "inhalation")
  take_acslx_inhal_output = read_excel("Data/Data_CF/Take_acslx_output.xlsx", 
                                       sheet = "inhalation")  
  
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_inhalation")
  
  # Time in minutes
  time_min <- out[,"time"]*60
  time <- time_min
  
  ntimes_acslx = length(take_acslx_inhal_output[["time"]])
  ntimes_template = length(out[,"time"])
  
  C_ven_out <- out[,"C_ven"]
  fat_out <- out[,"C_tc3"] * 0.9
  kid_out <- (out[,"A_ki"] + out[,"A_om"]) / (out[,"V_ki"] + out[,"V_om"])
  liv_out <- out[,"C_li"]
  
  print("The following values are calculated from the inhalation route models.")
  
  bl_acslx_model = data.frame(time_acslx_mod=c(take_acslx_inhal_output[,1]),
                              ven_bl_acslx_mod=c(take_acslx_inhal_output[,2]))
  bl_template_model = data.frame(time, C_ven_out)
  bl_acslx_model = bl_acslx_model[rowSums(bl_acslx_model[])>0,]
  df_acslx_temp_merge <- merge(na.omit(bl_acslx_model), 
                               na.omit(bl_template_model), by.x='time')
  
  err_bl_temp_acslx_inhal = max(abs(perc.diff(df_acslx_temp_merge[,"C_ven_out"], 
                                              df_acslx_temp_merge[,"blood_conc"])))
  
  print("Maximum percentage difference between template and acslx models")
  print(paste0("  in blood compartment:  ", err_bl_temp_acslx_inhal))
  
  
  fat_acslx_model = data.frame(time_acslx_mod=c(take_acslx_inhal_output[,1]),
                               fat_acslx_mod=c(take_acslx_inhal_output[,3]))
  fat_template_model = data.frame(time, fat_out)
  fat_acslx_model = fat_acslx_model[rowSums(fat_acslx_model[])>0,]
  fat_acslx_temp_merge <- merge(na.omit(fat_acslx_model), 
                                na.omit(fat_template_model), by.x='time')
  
  err_fat_temp_acslx_oral = max(abs(perc.diff(fat_acslx_temp_merge[,"fat_out"], 
                                              fat_acslx_temp_merge[,"fat_conc"])))
  
  print(paste0("  in fat compartment:    ", err_fat_temp_acslx_oral))
  
  
  kid_acslx_model = data.frame(time_acslx_mod=c(take_acslx_inhal_output[,1]),
                               kid_acslx_mod=c(take_acslx_inhal_output[,4]))
  kid_template_model = data.frame(time, kid_out)
  kid_acslx_model = kid_acslx_model[rowSums(kid_acslx_model[])>0,]
  kid_acslx_temp_merge <- merge(na.omit(kid_acslx_model), 
                                na.omit(kid_template_model), by.x='time')
  
  err_kid_temp_acslx_oral = max(abs(perc.diff(kid_acslx_temp_merge[,"kid_out"], 
                                              kid_acslx_temp_merge[,"kidney_conc"])))
  
  print(paste0("  in kidney compartment: ", err_kid_temp_acslx_oral))
  
  
  liv_acslx_model = data.frame(time_acslx_mod=c(take_acslx_inhal_output[,1]),
                               liv_acslx_mod=c(take_acslx_inhal_output[,5]))
  liv_template_model = data.frame(time, liv_out)
  liv_acslx_model = liv_acslx_model[rowSums(liv_acslx_model[])>0,]
  liv_acslx_temp_merge <- merge(na.omit(liv_acslx_model), 
                                na.omit(liv_template_model), by.x='time')
  
  err_liv_temp_acslx_oral = max(abs(perc.diff(liv_acslx_temp_merge[,"liv_out"], 
                                              liv_acslx_temp_merge[,"liver_conc"])))
  
  print(paste0("  in liver compartment:  ", err_liv_temp_acslx_oral))
}

chloroform.Take.oral.and.inhal.percent.diffs <- function(){
  # Calculate error: percent difference between template and acslx models
  # Discard first data point at time = 0, C_ven = 0
  
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet = "oral_inhalation")
  take_acslx_output = read_excel("Data/Data_CF/Take_acslx_output.xlsx", 
                                 sheet = "oral_inhalation")
  
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_oral_inh")
  
  # Time in minutes
  time_min <- out[,"time"]*60
  time <- time_min
  
  ntimes_acslx = length(take_acslx_output[["time"]])
  ntimes_template = length(out[,"time"])
  
  C_ven_out <- out[,"C_ven"]
  fat_out <- out[,"C_tc3"] * 0.9
  kid_out <- (out[,"A_ki"] + out[,"A_om"]) / (out[,"V_ki"] + out[,"V_om"])
  liv_out <- out[,"C_li"]
  
  print("The following values are calculated from the combined oral and inhalation route models.")
  
  bl_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                              ven_bl_acslx_mod=c(take_acslx_output[,2]))
  bl_template_model = data.frame(time, C_ven_out)
  bl_acslx_model = bl_acslx_model[rowSums(bl_acslx_model[])>0,]
  df_acslx_temp_merge <- merge(na.omit(bl_acslx_model), 
                               na.omit(bl_template_model), by.x='time')
  
  err_bl_temp_acslx_inhal = max(abs(perc.diff(df_acslx_temp_merge[,"C_ven_out"], 
                                              df_acslx_temp_merge[,"blood_conc"])))
  
  print("Maximum percentage difference between template and acslx models")
  print(paste0("  in blood compartment:  ", err_bl_temp_acslx_inhal))
  
  
  fat_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               fat_acslx_mod=c(take_acslx_output[,3]))
  fat_template_model = data.frame(time, fat_out)
  fat_acslx_model = fat_acslx_model[rowSums(fat_acslx_model[])>0,]
  fat_acslx_temp_merge <- merge(na.omit(fat_acslx_model), 
                                na.omit(fat_template_model), by.x='time')
  
  err_fat_temp_acslx_oral = max(abs(perc.diff(fat_acslx_temp_merge[,"fat_out"], 
                                              fat_acslx_temp_merge[,"fat_conc"])))
  
  print(paste0("  in fat compartment:    ", err_fat_temp_acslx_oral))
  
  
  kid_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               kid_acslx_mod=c(take_acslx_output[,4]))
  kid_template_model = data.frame(time, kid_out)
  kid_acslx_model = kid_acslx_model[rowSums(kid_acslx_model[])>0,]
  kid_acslx_temp_merge <- merge(na.omit(kid_acslx_model), 
                                na.omit(kid_template_model), by.x='time')
  
  err_kid_temp_acslx_oral = max(abs(perc.diff(kid_acslx_temp_merge[,"kid_out"], 
                                              kid_acslx_temp_merge[,"kidney_conc"])))
  
  print(paste0("  in kidney compartment: ", err_kid_temp_acslx_oral))
  
  
  liv_acslx_model = data.frame(time_acslx_mod=c(take_acslx_output[,1]),
                               liv_acslx_mod=c(take_acslx_output[,5]))
  liv_template_model = data.frame(time, liv_out)
  liv_acslx_model = liv_acslx_model[rowSums(liv_acslx_model[])>0,]
  liv_acslx_temp_merge <- merge(na.omit(liv_acslx_model), 
                                na.omit(liv_template_model), by.x='time')
  
  err_liv_temp_acslx_oral = max(abs(perc.diff(liv_acslx_temp_merge[,"liv_out"], 
                                              liv_acslx_temp_merge[,"liver_conc"])))
  
  print(paste0("  in liver compartment:  ", err_liv_temp_acslx_oral))
}
