#------------------------------------------------------------------------------
# CF_Take_scripts.R
#
# This file contains functions to recreate results for the Take chloroform 
# experiments modeled by Sasso et. al. (2013).
#
# Author: Bidya Prasad, December 2021
# Revisions for use with MCSimMod: Pau Schlosser, November 2025
#------------------------------------------------------------------------------

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)
library(readxl)

# Create model and load functions to (compile if needed and) run the PBPK model template.
source("run_template_model.R")

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
vcol = c("#440154FF", "#2A788EFF", "#7AD151FF") # viridis(3, begin = 0.0, end = 0.8)
pub.col <- vcol[2]; templ.col <- vcol[3]; paper.col <- vcol[2]
pub.lty <- "dashed"; templ.lty <- "solid"; paper.lty <- "dashed"

one.comp.plot <- function(temp,tissname,data,acslx,ylim=c(0.005,100)){
  # Function to plot results of PBPK Mode Template (temp) vs. corresponding Take
  # et al. data (data) and acslX results (acslx) for tissue named tissname. 
  # temp and acslx = c(time vector, tissue concentration vector)
  # data = c(times, min values, mean values, max values)
  plot(temp[,1], temp[,2], type="l", lwd=4, lty=templ.lty, cex=0.2,
       col=templ.col,  log="y", cex.main = 0.8, xlab="Time (min)", 
       ylab=paste(tissname,"Concentration (mg/L)"),
       xlim=c(0, 500), ylim=ylim, cex.lab = 1.25, yaxt="n", xaxt="n")
  axis(side=1, at=seq(from=0, to=500, by=100), cex.axis = 1.2)
  axis(side=2, at=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0),
       labels=c(0.001, 0.01, 0.1, 1.0, 10.0, 100.0), cex.axis = 1.2, las=1)
  data=data.frame(data); acslx=data.frame(acslx)
  points(data[,1], data[,2], type="p", pch=8, cex=1.5, col=pub.col)
  points(data[,1], data[,3], type="p", pch=19, cex=1.5, col=pub.col)
  points(data[,1], data[,4], type="p", pch=8, cex=1.5, col=pub.col)
  lines(acslx[,1], acslx[,2], lwd=4, cex = 0.2, lty=pub.lty, col=pub.col)
}

Take.comp.plot <- function(out,range,take_data,take_acslx,ylimf=c(0.005, 100.0)){
  # Function to create set of plots of PBPK Mode Template results (out) vs.
  # corresponding Take et al. data (take_data) and acslX results (take_acslx).
  # range = row range of out to plot.
  out <- out[range,] # Time range to be plotted
  time_min <- out$time*60 # Time in minutes
  par(mfrow = c(2, 2), mar = c(5, 5, 0, 0), oma = c(3, 0, 1, 2))
  one.comp.plot(temp=cbind(time_min,out$C_ven), tissname="Blood",
                data=take_data[,c("time","blood_min","blood_data","blood_max")],
                acslx=take_acslx[,c("time","blood_conc")]) 
  one.comp.plot(temp=cbind(time_min,out$C_tc3*0.9), tissname="Fat",
                data=take_data[,c("time","fat_min","fat_data","fat_max")],
                acslx=take_acslx[,c("time","fat_conc")], ylim=ylimf) 
  kid_out <- (out$A_ki+out$A_om)/(out$V_ki+out$V_om)
  one.comp.plot(temp=cbind(time_min,kid_out), tissname="Kidney",
                data=take_data[,c("time","kidney_min","kidney_data","kidney_max")],
                acslx=take_acslx[,c("time","kidney_conc")]) 
  one.comp.plot(temp=cbind(time_min,out$C_li), tissname="Liver",
                data=take_data[,c("time","liver_min","liver_data","liver_max")],
                acslx=take_acslx[,c("time","liver_conc")]) 
  par(mfrow = c(1,1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
  plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
  legend("bottomleft", c("Median Data", "Min/Max Data"), xpd = TRUE, 
         inset = c(0.15, -0.01), bty = "n", col = c(pub.col, pub.col),
         lty = c(NA,NA), pch = c(19,8), lwd = c(1,2), cex=1.12)
  legend("bottomleft", c("Sasso et al. (2013) Model", "Template Version"),
         xpd = TRUE, inset = c(0.57, -0.01), bty="n", col=c(pub.col, templ.col),
         lty = c(pub.lty, templ.lty), pch = c(NA,NA), lwd = c(2,3), cex=1.12)
}

chloroform.Take.oral <- function(){
  # Creates manuscript Figure S-5
  times = seq(from=0, to=600, by=0.1)/60 # Simulation times (min --> h).
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet = "oral")
  take_acslx <- read_excel("Data/Data_CF/Take_acslx_output.xlsx", sheet = "oral")
  # Simulates male rats exposed to an oral dose of chloroform
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_oral",
                  data.times = times)
  Take.comp.plot(out, range=10:5500, take_data, take_acslx)
}

plot.CF.Take.oral <- function(){
  svg(filename="plot.CF.Take.oral.svg", width=12, height=9, pointsize=12)
  chloroform.Take.oral()
  dev.off()  
}

chloroform.Take.inhalation <- function(){
  # Creates manuscript Figure S-6
  times = seq(from=0, to=600, by=0.1)/60 # Simulation times (min --> h)
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet="inhalation")
  take_acslx <- read_excel("Data/Data_CF/Take_acslx_output.xlsx", sheet="inhalation")
  # Simulates male rats exposed to an inhaled dose of chloroform
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_inhalation",
                  data.times = times)
  Take.comp.plot(out, range=5:4810, take_data, take_acslx)
}

plot.CF.Take.inh <- function(){
  svg(filename="plot.CF.Take.inh.svg", width=12, height=9, pointsize=12)
  chloroform.Take.inhalation()
  dev.off()  
}

chloroform.Take.oral.and.inh <- function(){
  # Reproduces results in manuscript Figure 9
   times = seq(from=0, to=600, by=0.1)/60 # Simulation times (min --> h)
  # Import data 
  take_data = read_excel("Data/Data_CF/Take_data.xlsx", sheet = "oral_inhalation")
  take_acslx = read_excel("Data/Data_CF/Take_acslx_output.xlsx", sheet="oral_inhalation")
  
  # Simulates male rats exposed to an inhaled dose of chloroform
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_oral_inh",
                  data.times = times)
  Take.comp.plot(out, range=7:6000, take_data, take_acslx, ylimf=c(0.005, 150.0))
}

plot.CF.Take.oral.inh <- function(){
  svg(filename="plot.CF.Take.oral.inh.svg", width=12, height=9, pointsize=12)
  chloroform.Take.oral.and.inh()
  dev.off()  
}

res.diff.calc <- function(out,acslx){
  # Calculate differences between PBPK Model Template ('out') and acslx results
  # for venous blood, fat, kidney and liver predictions.
  out <- data.frame(time=out$time*60, bl=out$C_ven, fat=out$C_tc3*0.9, 
                    kid=(out$A_ki+out$A_om)/(out$V_ki+out$V_om), li=out$C_li)
  res_merge <- na.omit(merge(out, acslx, by.x='time'))
  print("Maximum percentage difference between template and acslx models (rounded to 0.001%).",quote=FALSE)
  print(paste("  in blood compartment:", max.diff(res_merge$bl, res_merge$blood_conc)),quote=FALSE)
  print(paste("    in fat compartment:", max.diff(res_merge$fat, res_merge$fat_conc)),quote=FALSE)
  print(paste(" in kidney compartment:", max.diff(res_merge$kid, res_merge$kidney_conc)),quote=FALSE)
  print(paste("  in liver compartment:", max.diff(res_merge$li, res_merge$liver_conc)),quote=FALSE)
}

Take.oral.diffs <- function(){
  # Calculate error: percent difference between template and acslx models for 
  # Take oral exposure.
  
  # Import acslx results:
  acslx = read_excel("Data/Data_CF/Take_acslx_output.xlsx", sheet = "oral")
  # Get PBPK Mode Template results:
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx", 
                  model.param.sheetname = "Revised_rat_params", 
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_oral",
                  data.times=acslx$time/60)
  print("The following values are calculated from the oral route models.",
        quote=FALSE)
  res.diff.calc(out,acslx)
}

Take.inhal.diffs <- function(){
  # Calculate error: percent difference between template and acslx models for 
  # Take inhalation exposure.

  # Import acslx results:
  acslx = read_excel("Data/Data_CF/Take_acslx_output.xlsx", sheet="inhalation")  
  # Get PBPK Mode Template results:
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_inhalation",
                  data.times=acslx$time/60)
  print("The following values are calculated from the inhalation route models.",
        quote=FALSE)
  res.diff.calc(out,acslx)
}

Take.oral.and.inhal.diffs <- function(){
  # Calculate error: percent difference between template and acslx models for
  # Take combined oral and inhalation exposure.
  
  # Import acslx results:
  acslx = read_excel("Data/Data_CF/Take_acslx_output.xlsx", sheet="oral_inhalation")
  out <- PBPK_run(model.param.filename = "CF_template_parameters_Model.xlsx",
                  model.param.sheetname = "Revised_rat_params",
                  exposure.param.filename = "CF_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Take_oral_inh",
                  data.times=acslx$time/60)
  print("The following values are calculated from the combined oral and inhalation route models.", 
        quote=FALSE)
  res.diff.calc(out,acslx)
  }
