# DCM_scripts.R
#
# This file contains functions to recreate results for the DCM model.
#
# Author: Amanda Bernstein, December 2020
# Adapted for use with PBPK_template.model as revised for PFAS inhalation and 
# the MCSimMod package by Paul Schlosser, November 2025

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Load functions to run the PBPK model template.
source("run_template_model.R")

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
#vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

#vcol = c("#482576FF", "#25848EFF", "#7AD151FF") # viridis(3, begin = 0.1, end = 0.8)
vcol3 = c("#440154FF", "#2A788EFF", "#7AD151FF") # viridis(3, begin = 0.0, end = 0.8)

pub.col <- vcol3[2]
templ.col <- vcol3[3]

pub.lty <- "dashed"
templ.lty <- "solid"


DCM.IRIS.Table5.1 <- function(){
  # Creates manuscript Table S-1
  #
  # Simulates male and female F344 rats exposed to dichloromethane in drinking 
  # water for 2 years, and computes the amount metabolized by the GST and CYP 
  # pathways
  
  # IRIS results from: "Rat DW Serota 1986a_EPA.m"
  
  load(file = "Data/Data_DCM/DCM_Table5.1.Rdata") # Load copy of table from original model template
  s5.1 = table5.1
  
  daily.intake.m <- c(0, 6, 52, 125, 235)
  #daily.intake.f <- c(0, 6, 58, 136, 263)
  daily.intake <- c(daily.intake.m)#, daily.intake.f)
  #first five doses male, second five doses female
  met.dose.liv.gst <- rep(0,length(daily.intake))
  met.dose.liv.cyp <- rep(0,length(daily.intake))
  IRIS.met.dose.liv.gst <- c(0, 2.6, 81.5, 276.5, 612.1)#, 
                             #0, 2.47, 93.3, 307.8, 705.6)
  IRIS.met.dose.liv.cyp <- c(0, 131.6, 723.9, 1170.5, 1548.0)#, 
                             #0, 132.8, 801.4, 1261.5, 1672.4)
  
  water.dose.frac <- c(0.233, 0.1, 0.1, 0.1, 0.233, 0.234) #IRIS mouse
  
  table5.1 <- data.frame(daily.intake, met.dose.liv.gst, IRIS.met.dose.liv.gst,
                         met.dose.liv.cyp, IRIS.met.dose.liv.cyp)
  idx <- 1
 
  for (ii in daily.intake.m){
    
    out <- PBPK_run(model.param.filename = "DCM_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_rat_VarC", 
                    exposure.param.filename = "DCM_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Oral_Periodic_IRIS_T5.1",
                    adj.parms = c(dose_water = ii),
                    water.dose.frac = water.dose.frac)
    
    # Compute daily averages over the last week of the simulation
    last <- length(out$A_met_1st_li)
    lastweek <- 1681
    
    liverfrac <- 0.04
    BW <- 0.38
    livervolume <- liverfrac*BW
    
    # GST pathway in liver (mg DCM metabolized via GST pathway/L tissue/day)
    table5.1$met.dose.liv.gst[idx] <- (out$A_met_1st_li[last] - out$A_met_1st_li[lastweek])/(7*livervolume)
    s5.1$met.dose.liv.gst[idx] = s5.1$met.dose.liv.gst[idx] - table5.1$met.dose.liv.gst[idx]
    
    # CYP pathway in liver (mg DCM metabolized via CYP pathway/L tissue/day)
    table5.1$met.dose.liv.cyp[idx] <- (out$A_met_sat_li[last] - out$A_met_sat_li[lastweek])/(7*livervolume)
    s5.1$met.dose.liv.cyp[idx] = s5.1$met.dose.liv.cyp[idx] - table5.1$met.dose.liv.cyp[idx]
    
    idx <- idx + 1
  }
  table5.1[(1:idx)+idx,] <- s5.1

  # for (ii in daily.intake.f){
  #   
  #   out <- PBPK_run(model.param.filename = "DCM_template_parameters_Model.xlsx",
  #                   model.param.sheetname = "IRIS_model_rat_VarC", 
  #                   exposure.param.filename = "DCM_template_parameters_Exposure.xlsx", 
  #                   exposure.param.sheetname = "Oral_Periodic_IRIS_T5.1",
  #                   adj.parms = c(dose_water = ii, BW = 0.229))
  #   
  #   # GST pathway
  #   table5.1$met.dose.liv.gst[idx] <- (out$A_met_1st_li[3361] - out$A_met_1st_li[1681])/(7*0.04*0.38)
  #   
  #   # CYP pathway
  #   table5.1$met.dose.liv.cyp[idx] <- (out$A_met_sat_li[3361] - out$A_met_sat_li[1681])/(7*0.04*0.38)
  #   
  #   idx <- idx + 1
  # }
  
  return(table5.1)
  
}

DCM.IRIS.Table5.11 <- function(){
  # Creates manuscript Table S-2
  #
  # Simulates male B6C3F1 mice exposed to dichloromethane in drinking water for 
  # 2 years, and computes the amount metabolized by the GST pathway
  
  daily.intake <- c(0, 61, 124, 177, 234)
  met.dose.body <- rep(0,length(daily.intake))
  IRIS.met.dose.body <- c(0, 0.73, 2.65, 4.68, 7.1)
  
  water.dose.frac <- c(0.233, 0.1, 0.1, 0.1, 0.233, 0.234) #IRIS mouse
  
  table5.11 <- data.frame(daily.intake, met.dose.body, IRIS.met.dose.body)
  idx <- 1
  
  for (ii in daily.intake){
  
  out <- PBPK_run(model.param.filename = "DCM_template_parameters_Model.xlsx",
                  model.param.sheetname = "IRIS_model_mouse", 
                  exposure.param.filename = "DCM_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Oral_Periodic_IRIS_T5.11",
                  adj.parms = c(dose_water = ii), 
                  water.dose.frac = water.dose.frac)
  
  # Compute daily averages over the last week of the simulation
  last <- length(out$A_met_1st)
  lastweek <- 1681
  BW <- 0.0373
  
    table5.11$met.dose.body[idx] <- (out$A_met_1st[last] - out$A_met_1st[lastweek])/(7*BW)
    idx <- idx + 1
  }
  
  return(table5.11)
  
}

DCM.IRIS.FigC3 <- function(img.name = NULL){
  # Creates manuscript Figure 3
  #
  # Simulates 3 rats exposed to dichloromethane via inhalation in a 9-L closed 
  # chamber
  
  # Load Gargas inhalation data
  dataC3 <- read.csv(file = "Data/Data_DCM/gargas-inh-data2_NEW.csv", fileEncoding="UTF-8-BOM")
  
  # Initial concentration in ppm
  conc.ppm <- c(107.0, 498.0, 1028.0, 3206.0)
  
  out.time.hr <- rep(0,1)
  out.all <- NULL
  
  for (ii in conc.ppm){
    
    out <- PBPK_run(model.param.filename = "DCM_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_rat_VarC", 
                    exposure.param.filename = "DCM_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Inh_Closed_IRIS_FigC3",
                    adj.parms = c(Conc_init = ii, BW = 0.225),
                    data.times = dataC3$Atime)
    
    out.all.time <- out$time.hr
    out.all <- cbind(out.all, out$C_chppm)
    
  }
  
  # Calculate error - percent difference between template and IRIS sims
  print("Max percent difference for chamber concentration")
  err1 = max(abs(perc.diff(model = out.all[,1], data = dataC3$C1)))
  print(paste0("Max. percent difference for 100 ppm: ", err1))
  
  err5 = max(abs(perc.diff(model = out.all[,2], data = dataC3$C5)))
  print(paste0("Max. percent difference for 500 ppm: ", err5))
  
  err10 = max(abs(perc.diff(model = out.all[,3], data = dataC3$C10)))
  print(paste0("Max. percent difference for 1000 ppm: ", err10))
  
  err30 = max(abs(perc.diff(model = out.all[,4], data = dataC3$C30)))
  print(paste0("Max. percent difference for 3000 ppm: ", err30))
  
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=5, width=6, units="in")
  }
  
  plot(1,1, type ="n", xlab = "Time (hr)", ylab = "Chamber Concentration (ppm)", 
       xlim = c(0,4.5), ylim = c(0,500))
  lines(out.all.time,out.all[,1], col = templ.col, lty = templ.lty, lwd = 3)
  lines(out.all.time,out.all[,2], col = templ.col, lty = templ.lty, lwd = 3)
  lines(out.all.time,out.all[,3], col = templ.col, lty = templ.lty, lwd = 3)
  lines(dataC3$Atime,dataC3$C1, col = pub.col, lty = pub.lty, lwd = 2)
  lines(dataC3$Atime,dataC3$C5, col = pub.col, lty = pub.lty, lwd = 2)
  lines(dataC3$Atime,dataC3$C10, col = pub.col, lty = pub.lty, lwd = 2)
  points(dataC3$dch1time,dataC3$dch1, pch = 19, col = pub.col)
  points(dataC3$dch5time,dataC3$dch5, pch = 19, col = pub.col)
  points(dataC3$dch10time,dataC3$dch10, pch = 19, col = pub.col)
  
  legend("topright", legend = c("Published Data", "EPA IRIS Model", 
                                  "Template Version"),
         pch = c(19,NA,NA), lty = c(NA, pub.lty, templ.lty), lwd = c(NA,2,3), 
         col = c(pub.col, pub.col, templ.col))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
}
