# DCM_scripts.R
#
# This file contains functions to recreate results for the DCM model.
#
# Author: Amanda Bernstein, December 2020
# Adapted for use with PBPK_template.model as revised for PFAS inhalation and 
# the MCSimMod package by Paul Schlosser, November 2025
# Table functions below now read in Tables produced by the non-MCSimMod package
# and append the differences between those and the current results.

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Load functions to run the PBPK model template.
source("run_template_model.R")

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
#vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

#vcol = c("#482576FF", "#25848EFF", "#7AD151FF") # viridis(3, begin = 0.1, end = 0.8)
vcol3 = c("#440154FF", "#2A788EFF", "#7AD151FF") # viridis(3, begin = 0.0, end = 0.8)
pub.col <- vcol3[2]; templ.col <- vcol3[3]; pub.lty <- "dashed"; templ.lty <- "solid"

DCM.IRIS.Table5.1 <- function(){
  # Creates manuscript Table S-1
  #
  # Simulates male and female F344 rats exposed to dichloromethane in drinking 
  # water for 2 years, and computes the amount metabolized by the GST and CYP 
  # pathways
  
  # IRIS results from: "Rat DW Serota 1986a_EPA.m"
  
  s5.1 <- readRDS("Data/Data_DCM/DCM_Table5.1.rds")
  
  daily.intake.m <- c(0, 6, 52, 125, 235)
  #daily.intake.f <- c(0, 6, 58, 136, 263)
  daily.intake <- c(daily.intake.m)#, daily.intake.f)
  #first five doses male, second five doses female
  met.dose.liv.gst <- rep(0,length(daily.intake))
  met.dose.liv.cyp <- rep(0,length(daily.intake))
  IRIS.met.dose.liv.gst <- c(0, 2.6, 81.5, 276.5, 612.1)#, 
                             #0, 2.47, 93.3, 307.8, 705.6)
  IRIS.met.dose.liv.cyp <- c(0, 131.6, 723.9, 1170.5, 1548.0)#, 
                             #0, 132.8, 801.4, 1261.5, 1672.4)
  
  water.dose.frac <- c(0.233, 0.1, 0.1, 0.1, 0.233, 0.234) #IRIS mouse
  
  table5.1 <- data.frame(daily.intake, met.dose.liv.gst, IRIS.met.dose.liv.gst,
                         met.dose.liv.cyp, IRIS.met.dose.liv.cyp)
  
  nd = length(daily.intake.m)
  for (ii in 1:nd){ # Results for males
    out <- PBPK_run(model.param.filename = "DCM_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_rat_VarC", 
                    exposure.param.filename = "DCM_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Oral_Periodic_IRIS_T5.1",
                    adj.parms = c(dose_water = daily.intake.m[ii]),
                    water.dose.frac = water.dose.frac)
    
    # Compute daily averages over the last week of the simulation
    last <- length(out$A_met_1st_li)
    lastweek <- which(out$time.days==(out$time.days[last]-7))

    # GST pathway in liver (mg DCM metabolized via GST pathway/L tissue/day)
    table5.1$met.dose.liv.gst[ii] <- (out$A_met_1st_li[last] - out$A_met_1st_li[lastweek])/(7*out$V_li[last])
    
    # CYP pathway in liver (mg DCM metabolized via CYP pathway/L tissue/day)
    table5.1$met.dose.liv.cyp[ii] <- (out$A_met_sat_li[last] - out$A_met_sat_li[lastweek])/(7*out$V_li[last])
    if (ii>1) {
      s5.1$met.dose.liv.gst[ii] = s5.1$met.dose.liv.gst[ii]/table5.1$met.dose.liv.gst[ii] -1
      s5.1$met.dose.liv.cyp[ii] = s5.1$met.dose.liv.cyp[ii]/table5.1$met.dose.liv.cyp[ii] -1
    }
  }
  table5.1[(1:nd)+nd,] <- s5.1
  com=print("Rows 6-10 below are relative error between current results and previous PBPK Model Template.",quote=FALSE)
  com
  # for (ii in daily.intake.f){ # Results for females
  #   out <- PBPK_run(model.param.filename = "DCM_template_parameters_Model.xlsx",
  #                   model.param.sheetname = "IRIS_model_rat_VarC", 
  #                   exposure.param.filename = "DCM_template_parameters_Exposure.xlsx", 
  #                   exposure.param.sheetname = "Oral_Periodic_IRIS_T5.1",
  #                   adj.parms = c(dose_water = ii, BW = 0.229))
  #   # GST pathway
  #   table5.1$met.dose.liv.gst[idx] <- (out$A_met_1st_li[3361] - out$A_met_1st_li[1681])/(7*0.04*0.38)
  #   # CYP pathway
  #   table5.1$met.dose.liv.cyp[idx] <- (out$A_met_sat_li[3361] - out$A_met_sat_li[1681])/(7*0.04*0.38)
  #   idx <- idx + 1
  # }
  
  return(table5.1)
  
}

DCM.IRIS.Table5.11 <- function(){
  # Creates manuscript Table S-2
  #
  # Simulates male B6C3F1 mice exposed to dichloromethane in drinking water for 
  # 2 years, and computes the amount metabolized by the GST pathway
  
  s5.11 = readRDS("Data/Data_DCM/DCM_Table5.11.rds")
  
  daily.intake <- c(0, 61, 124, 177, 234)
  met.dose.body <- rep(0,length(daily.intake))
  IRIS.met.dose.body <- c(0, 0.73, 2.65, 4.68, 7.1)
  water.dose.frac <- c(0.233, 0.1, 0.1, 0.1, 0.233, 0.234) #IRIS mouse
  
  table5.11 <- data.frame(daily.intake, met.dose.body, IRIS.met.dose.body)

  nd = length(daily.intake)
  for (ii in 1:nd){
    out <- PBPK_run(model.param.filename = "DCM_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_mouse", 
                    exposure.param.filename = "DCM_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Oral_Periodic_IRIS_T5.11",
                    adj.parms = c(dose_water = daily.intake[ii]), 
                    water.dose.frac = water.dose.frac)
    # Compute daily averages over the last week of the simulation
    last <- length(out$A_met_1st)
    lastweek <- which(out$time.days==(out$time.days[last]-7))
    table5.11$met.dose.body[ii] <- (out$A_met_1st[last] - out$A_met_1st[lastweek])/(7*out$BW_out[1])
    if (ii>1) s5.11$met.dose.body[ii] =s5.11$met.dose.body[ii]/table5.11$met.dose.body[ii] -1
  }
  table5.11[(1:nd)+nd,] <- s5.11
  return(table5.11)
}

DCM.IRIS.FigC3 <- function(img.name = NULL){
  # Creates manuscript Figure 3
  #
  # Simulates 3 rats exposed to dichloromethane via inhalation in a 9-L closed 
  # chamber
  
  # Load Gargas inhalation data
  dataC3 <- read.csv(file = "Data/Data_DCM/gargas-inh-data2_NEW.csv", fileEncoding="UTF-8-BOM")
  # Initial concentration in ppm
  conc.ppm <- c(107.0, 498.0, 1028.0, 3206.0)
  out.all <- NULL
  for (ii in conc.ppm){
    
    out <- PBPK_run(model.param.filename = "DCM_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_rat_VarC", 
                    exposure.param.filename = "DCM_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Inh_Closed_IRIS_FigC3",
                    adj.parms = c(Conc_init = ii, BW = 0.225),
                    data.times = dataC3$Atime)
    out.all <- cbind(out.all, out$C_chppm)
  }
  
  # Calculate error - percent difference between template and IRIS sims
  print("Max percent difference for chamber concentration (rounded to 3 significant figures)",
        quote=FALSE)
  print(paste0("Max. percent difference for 100 ppm: ", 
               max.diff(model=out.all[,1], data=dataC3$C1)), quote=FALSE)
  print(paste0("Max. percent difference for 500 ppm: ", 
               max.diff(model=out.all[,2], data=dataC3$C5)), quote=FALSE)
  print(paste0("Max. percent difference for 1000 ppm: ", 
               max.diff(model=out.all[,3], data=dataC3$C10)), quote=FALSE)
  print(paste0("Max. percent difference for 3000 ppm: ", 
               max.diff(model=out.all[,4], data=dataC3$C30)), quote=FALSE)
  
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=5, width=6, units="in")
  }
  
  plot(1,1, type ="n", xlab = "Time (hr)", ylab = "Chamber Concentration (ppm)", 
       xlim = c(0,4.5), ylim = c(0,500))
  lines(out$time,out.all[,1], col = templ.col, lty = templ.lty, lwd = 3)
  lines(out$time,out.all[,2], col = templ.col, lty = templ.lty, lwd = 3)
  lines(out$time,out.all[,3], col = templ.col, lty = templ.lty, lwd = 3)
  lines(dataC3$Atime,dataC3$C1, col = pub.col, lty = pub.lty, lwd = 2)
  lines(dataC3$Atime,dataC3$C5, col = pub.col, lty = pub.lty, lwd = 2)
  lines(dataC3$Atime,dataC3$C10, col = pub.col, lty = pub.lty, lwd = 2)
  points(dataC3$dch1time,dataC3$dch1, pch = 19, col = pub.col)
  points(dataC3$dch5time,dataC3$dch5, pch = 19, col = pub.col)
  points(dataC3$dch10time,dataC3$dch10, pch = 19, col = pub.col)
  
  legend("topright", legend = c("Published Data", "EPA IRIS Model", 
                                  "Template Version"),
         pch = c(19,NA,NA), lty = c(NA, pub.lty, templ.lty), lwd = c(NA,2,3), 
         col = c(pub.col, pub.col, templ.col))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
}
