# methanol_scripts.R
#
# This file contains functions to recreate results for the methanol model.
#
# Author: Amanda Bernstein, February 2021

# Set working directory to the directory containing this file.
script.dir = dirname(sys.frame(1)$ofile)
setwd(script.dir)

# Load functions to run the PBPK model template.
source("run_template_model.R")

old.par <- par(no.readonly = TRUE)

# Save some colors from the viridis palette. This vector of color-identification
# strings was generated by calling the function "viridis" from the package
# "viridis" with the argument "5"; i.e., "viridis(5)".
#vcol = c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")

#vcol = c("#482576FF", "#25848EFF", "#7AD151FF") # viridis(3, begin = 0.1, end = 0.8)
vcol3 = c("#440154FF", "#2A788EFF", "#7AD151FF") # viridis(3, begin = 0.0, end = 0.8)
vcol4 = c("#440154FF", "#39568CFF", "#1F988BFF", "#7AD151FF") # viridis(4, begin = 0.0, end = 0.8)
vcol5 = c("#440154FF", "#414487FF", "#2A788EFF", "#22A884FF", "#7AD151FF") # viridis(5, begin = 0.0, end = 0.8)
vcol7 = c("#440154FF", "#472F7DFF", "#39568CFF", "#2A788EFF", "#1F988BFF", 
          "#35B779FF", "#7AD151FF") # viridis(7, begin = 0.0, end = 0.8)


pub.col <- vcol3[2]
templ.col <- vcol3[3]

pub.col5.1 <- vcol5[1]
pub.col5.2 <- vcol5[2]
templ.col5.1 <- vcol5[4]
templ.col5.2 <- vcol5[5]

pub.col7.1 <- vcol7[1]
pub.col7.2 <- vcol7[2]
pub.col7.3 <- vcol7[3]
templ.col7.1 <- vcol7[5]
templ.col7.2 <- vcol7[6]
templ.col7.3 <- vcol7[7]

pub.lty <- "dashed"
templ.lty <- "solid"

methanol.IRIS.FigB3 <- function(){
  # Simulates female Sprague-Dawley rats exposed to methanol via a bolus IV dose
  
  # Import data and IRIS simulations
  data2500 <- read.csv(file = "Data/Data_Methanol/rat_Ward_iv_25.csv", header = FALSE)
  names(data2500) <- c("time", "C_ven")
  data500 <- read.csv(file = "Data/Data_Methanol/Pollack_500mg_iv.csv", header = FALSE)
  names(data500) <- c("time", "C_ven")
  data100 <- read.csv(file = "Data/Data_Methanol/rat_Ward_iv_1.csv", header = FALSE)
  names(data100) <- c("time", "C_ven")
  
  sim2500 <- read.csv(file = "Data/Data_Methanol/IRIS_FigB3_r2500.csv", header = FALSE)
  names(sim2500) <- c("time", "C_ven")
  sim500 <- read.csv(file = "Data/Data_Methanol/IRIS_FigB3_r500.csv", header = FALSE)
  names(sim500) <- c("time", "C_ven")
  sim100 <- read.csv(file = "Data/Data_Methanol/IRIS_FigB3_r100.csv", header = FALSE)
  names(sim100) <- c("time", "C_ven")
  
  # Read in background blood concentration for use in plotting
  all.parms <- NULL
  exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx"
  exposure.param.sheetname = "Ward_rat_iv_100"
  all.exposure.parms <- load.exposure.parameters(filename = exposure.param.filename, sheetname = exposure.param.sheetname, parms = all.parms$model_parms)
  bgd=all.exposure.parms$C_ven_SS  # C_ven_ss is the non-exposed "background" level in the model.
  
  iv_doses <- c(100, 500, 2500)
  
  out.time.hr <- rep(0,1)
  out.all <- NULL
  
  for (ii in iv_doses){
    
    out <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_rat", 
                    exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Ward_rat_iv_100",
                    adj.parms = c(iv_dose = ii), data.times = sim2500[["time"]])
    
    out.all.time <- out$time.hr
    out.all <- cbind(out.all, out$C_ven) # Results with background level subtracted
    
  }
  
  # Calculate error - percent difference between template and IRIS sims
  v=match(sim100[["time"]],out.all.time); 
  err100 = max(abs(perc.diff(model = out.all[v,1], data = sim100[,"C_ven"])))
  print(paste0("Max. percent difference for 100 mg/kg: ", err100))
  
  # Create Figure B3 from IRIS tox report
  plot(NULL, type="n", log = "y", ylim = c(1,10000), xlim = c(0,50),
       xlab = "Time (hr)", ylab = "Concentration of MeOH in Venous Blood (mg/L)")
  
  # Note, simulations are plotted with the background concentration of 3 mg/L in 
  #  venous blood subtracted out
  lines(out.all.time, out.all[,1]-bgd, col = "black", lwd = 2)
  points(data100[["time"]], data100[["C_ven"]], col = "black")
  lines(sim100[["time"]], sim100[["C_ven"]]-bgd, col = "red", lty = "dashed", lwd = 2)
  
  lines(out.all.time, out.all[,2]-bgd, col = "darkgreen", lwd = 2)
  points(data500[["time"]], data500[["C_ven"]], col = "darkgreen")
  lines(sim500[["time"]], sim500[["C_ven"]]-bgd, col = "red", lty = "dashed", lwd = 2)
  
  lines(out.all.time, out.all[,3]-bgd, col = "blue", lwd = 2)
  points(data2500[["time"]], data2500[["C_ven"]], col = "blue")
  lines(sim2500[["time"]], sim2500[["C_ven"]]-bgd, col = "red", lty = "dashed", lwd = 2)
  
  legend("bottomright", legend = c("100 mg/kg", "500 mg/kg", "2500 mg/kg"),
         col = c("black", "darkgreen", "blue"), lty = c(1, 1, 1))
  
}

methanol.IRIS.FigB4A <- function(img.name = NULL){
  # Creates manuscript Figure 4
  #
  # Simulates female Sprague-Dawley rats exposed to a constant concentration of 
  # methanol via inhalation for 8 hours (end simulation after 8.5 hours)
  
  # Import data and IRIS simulations
  data1k <- read.csv(file = "Data/Data_Methanol/RatInh_1K.csv", header = FALSE)
  names(data1k) <- c("time", "C_ven")
  data5k <- read.csv(file = "Data/Data_Methanol/RatInh_5K.csv", header = FALSE)
  names(data5k) <- c("time", "C_ven")
  data10k <- read.csv(file = "Data/Data_Methanol/RatInh_10K.csv", header = FALSE)
  names(data10k) <- c("time", "C_ven")
  data15k <- read.csv(file = "Data/Data_Methanol/RatInh_15K.csv", header = FALSE)
  names(data15k) <- c("time", "C_ven")
  data20k <- read.csv(file = "Data/Data_Methanol/RatInh_20K.csv", header = FALSE)
  names(data20k) <- c("time", "C_ven")
  
  #simB4A <- read.csv(file = "Data/Data_Methanol/FigB4A.csv", header = FALSE) #BW=0.345
  simB4A <- read.csv(file = "Data/Data_Methanol/FigB4A_0.3.csv", header = FALSE)
  #simB4A <- read.csv(file = "Data/Data_Methanol/FigB4A_0.25.csv", header = FALSE)
  names(simB4A) <- c("time", "C_ven1k", "C_ven5k", "C_ven10k", "C_ven15k", "C_ven20k")
  
  
  # Run simulations
  concentrations <- c(1000, 5000, 10000, 15000, 20000)
  
  out.time.hr <- rep(0,1)
  out.all <- NULL
  
  all.parms <- NULL
  exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx"
  exposure.param.sheetname = "Perkins_rat_inh_1000ppm"
  all.exposure.parms <- load.exposure.parameters(filename = exposure.param.filename, sheetname = exposure.param.sheetname, parms = all.parms$model_parms)
  bgd=all.exposure.parms$C_ven_SS  # C_ven_ss is the non-exposed "background" level in the model.
  
  for (ii in concentrations){
    
    out <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_rat",
                    exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Perkins_rat_inh_1000ppm",
                    adj.parms = c(Conc_init = ii), data.times = simB4A[["time"]])
    
    out.all.time <- out$time.hr
    out.all <- cbind(out.all, out$C_ven)
    
  }
  
  # Calculate error - percent difference between template and IRIS sims
  v=match(simB4A[["time"]],out.all.time)
  err1k = max(abs(perc.diff(model = out.all[v,1], data = simB4A[,"C_ven1k"])))
  print(paste0("Max. percent difference for 1000 ppm: ", err1k))
  
  err5k = max(abs(perc.diff(model = out.all[v,2], data = simB4A[,"C_ven5k"])))
  print(paste0("Max. percent difference for 5000 ppm: ", err5k))
  
  err10k = max(abs(perc.diff(model = out.all[v,3], data = simB4A[,"C_ven10k"])))
  print(paste0("Max. percent difference for 10000 ppm: ", err10k))
  
  err15k = max(abs(perc.diff(model = out.all[v,4], data = simB4A[,"C_ven15k"])))
  print(paste0("Max. percent difference for 15000 ppm: ", err15k))
  
  err20k = max(abs(perc.diff(model = out.all[v,5], data = simB4A[,"C_ven20k"])))
  print(paste0("Max. percent difference for 20000 ppm: ", err20k))
  
  
  # Create Figure B4, panel A from IRIS tox report
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=5, width=6, units="in")
  }
  
  plot(NULL, type="n", ylim = c(1,4000), xlim = c(0,8.5),
       xlab = "Time (hr)", ylab = "Concentration of MeOH in Venous Blood (mg/L)")
  
  # Note, simulations are plotted with the background concentration of 3 mg/L in 
  #  venous blood subtracted out
  lines(out.all.time, out.all[,1]-bgd, col = templ.col, lty = templ.lty, lwd = 3)
  points(data1k[["time"]], data1k[["C_ven"]], pch = 19, col = pub.col)
  lines(simB4A[["time"]], simB4A[["C_ven1k"]]-bgd, col = pub.col, lty = pub.lty, lwd = 2)
  
  lines(out.all.time, out.all[,2]-bgd, col = templ.col, lty = templ.lty, lwd = 3)
  points(data5k[["time"]], data5k[["C_ven"]], pch = 19, col = pub.col)
  lines(simB4A[["time"]], simB4A[["C_ven5k"]]-bgd, col = pub.col, lty = pub.lty, lwd = 2)
  
  lines(out.all.time, out.all[,3]-bgd, col = templ.col, lty = templ.lty, lwd = 3)
  points(data10k[["time"]], data10k[["C_ven"]], pch = 19, col = pub.col)
  lines(simB4A[["time"]], simB4A[["C_ven10k"]]-bgd, col = pub.col, lty = pub.lty, lwd = 2)
  
  lines(out.all.time, out.all[,4]-bgd, col = templ.col, lty = templ.lty, lwd = 3)
  points(data15k[["time"]], data15k[["C_ven"]], pch = 19, col = pub.col)
  lines(simB4A[["time"]], simB4A[["C_ven15k"]]-bgd, col = pub.col, lty = pub.lty, lwd = 2)
  
  lines(out.all.time, out.all[,5]-bgd, col = templ.col, lty = templ.lty, lwd = 3)
  points(data20k[["time"]], data20k[["C_ven"]], pch = 19, col = pub.col)
  lines(simB4A[["time"]], simB4A[["C_ven20k"]]-bgd, col = pub.col, lty = pub.lty, lwd = 2)
  
  legend("topleft", legend = c("Published Data", "EPA IRIS Model", "Template Version"),
         col = c(pub.col, pub.col, templ.col), lty = c(NA, pub.lty, templ.lty),
         pch = c(19, NA, NA), lwd = c(1, 2, 3))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
}

methanol.IRIS.FigB4B <- function(img.name = NULL){
  # Creates manuscript Figure S-2
  #
  # Simulates female Sprague-Dawley rats exposed to a constant concentration of 
  # methanol via inhalation for 8 hours
  
  # Import data and IRIS simulations
  dat.conc = c(1000, 5000, 10000, 15000, 20000)
  dat.cven = c(83, 1047, 1656, 2667, 3916)
  
  #simB4B <- read.csv(file = "Data/Data_Methanol/FigB4B.csv", header = FALSE) #BW=0.345
  simB4B <- read.csv(file = "Data/Data_Methanol/FigB4B_0.3.csv", header = FALSE)
  names(simB4B) <- c("Conc", "C_ven")
  
  
  # Run simulations
  concentrations1 <- seq(from = 100, to = 1000, by = 100)
  concentrations2 <- seq(from = 2000, to = 20000, by = 1000)
  concentrations <- c(concentrations1, concentrations2)
  
  c.venous <- rep(0,length(concentrations))
  out.conc <- data.frame(concentrations, c.venous)
  idx = 1
  
  for (ii in concentrations){
    
    out <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_rat",
                    exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Perkins_rat_inh_8hr",
                    adj.parms = c(Conc_init = ii))
    
    out.conc$c.venous[idx] <- out$C_ven[(length(out$C_ven))]
    
    idx = idx + 1
    
  }
  
  
  # Calculate error - percent difference between template and IRIS sims
  err = max(abs(perc.diff(model = out.conc$c.venous, data = simB4B[,"C_ven"])))
  print(paste0("Max. percent difference: ", err))
  
  
  # Create Figure B4, panel B from IRIS tox report 
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=5, width=6, units="in")
  }
  
  plot(NULL, type="n", ylim = c(1,4000), xlim = c(0,20000),
       xlab = "Exposure Concentration (ppm)", ylab = "Concentration of MeOH in Venous Blood at 8 hr (mg/L)")
  
  lines(out.conc$concentrations, out.conc$c.venous, col = templ.col, lty = templ.lty, lwd = 3)
  points(dat.conc, dat.cven, pch = 19, col = pub.col)
  lines(simB4B[["Conc"]], simB4B[["C_ven"]], col = pub.col, lty = pub.lty, lwd = 2)
  
  legend("topleft", legend = c("Published Data", "EPA IRIS Model", "Template Version"),
        col = c(pub.col, pub.col, templ.col), lty = c(NA, pub.lty, templ.lty), 
        pch = c(19, NA, NA), lwd = c(1, 2, 3))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
}

methanol.IRIS.FigB5 <- function(img.name = NULL){
  # Creates manuscript Figure 5 (100 mg/kg dose) and Figure S-3 (2500 mg/kg dose)
  #
  # Simulates female Sprague-Dawley rats exposed to an oral dose of methanol
  
  # Import data and IRIS simulations
  dataB5_2500 = read.csv(file = "Data/Data_Methanol/ratoral25.csv", header = FALSE)
  names(dataB5_2500) <- c("Time", "C_ven")
  
  dataB5_100 = read.csv(file = "Data/Data_Methanol/ratoral1.csv", header = FALSE)
  names(dataB5_100) <- c("Time", "C_ven")
  
  simB5_2500 <- read.csv(file = "Data/Data_Methanol/FigB5A.csv", header = FALSE)
  names(simB5_2500) <- c("Time_2gi", "C_ven_2gi", "Time_1gi", "C_ven_1gi")
  
  simB5_100 <- read.csv(file = "Data/Data_Methanol/FigB5B.csv", header = FALSE)
  names(simB5_100) <- c("Time_2gi", "C_ven_2gi", "Time_1gi", "C_ven_1gi")
  
  all.parms <- NULL
  exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx"
  exposure.param.sheetname = "Ward_oral_2500"
  all.exposure.parms <- load.exposure.parameters(filename = exposure.param.filename, sheetname = exposure.param.sheetname, parms = all.parms$model_parms)
  bgd=all.exposure.parms$C_ven_SS  # C_ven_ss is the non-exposed “background” level in the model.
  
  
  # Run simulations
  out2500_2gi <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_rat_2gi",
                    exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Ward_oral_2500",
                    data.times = simB5_2500[["Time_2gi"]])
  
  out2500_1gi <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                          model.param.sheetname = "IRIS_model_rat_1gi",
                          exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                          exposure.param.sheetname = "Ward_oral_2500",
                          data.times = simB5_2500[["Time_1gi"]])
  
  out100_2gi <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                      model.param.sheetname = "IRIS_model_rat_2gi",
                      exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                      exposure.param.sheetname = "Ward_oral_100",
                      data.times = simB5_100[["Time_2gi"]])
  
  out100_1gi <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                         model.param.sheetname = "IRIS_model_rat_1gi",
                         exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                         exposure.param.sheetname = "Ward_oral_100",
                         data.times = simB5_100[["Time_1gi"]])
  
  
  # Calculate error - percent difference between template and IRIS sims
  # Discard first data point at time = 0, C_ven = 0
  v=match(simB5_2500[["Time_2gi"]],out2500_2gi$time.hr)
  err2500_2gi = max(abs(perc.diff(model = out2500_2gi[v,"C_ven"], 
                                  data = simB5_2500[,"C_ven_2gi"])))
  print(paste0("Max. percent difference for 2500 mg/kg (2 gi comp.): ", err2500_2gi))
  
  v=match(simB5_2500[["Time_1gi"]],out2500_1gi$time.hr)
  err2500_1gi = max(abs(perc.diff(model = out2500_1gi[v,"C_ven"], 
                                  data = simB5_2500[,"C_ven_1gi"])))
  print(paste0("Max. percent difference for 2500 mg/kg (1 gi comp.): ", err2500_1gi))
  
  v=match(simB5_100[["Time_2gi"]],out100_2gi$time.hr)
  err100_2gi = max(abs(perc.diff(model = out100_2gi[v,"C_ven"], 
                                 data = simB5_100[,"C_ven_2gi"])))
  print(paste0("Max. percent difference for 100 mg/kg (2 gi comp.): ", err100_2gi))
  
  v=match(simB5_100[["Time_1gi"]],out100_1gi$time.hr)
  err100_1gi = max(abs(perc.diff(model = out100_1gi[v,"C_ven"], 
                                 data = simB5_100[,"C_ven_1gi"])))
  print(paste0("Max. percent difference for 100 mg/kg (1 gi comp.): ", err100_1gi))
  
  
  # Create Figure B5, panel A from IRIS tox report 
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=4, width=7, units="in")
  }
  
  par(mfrow=c(1, 2), mar = c(5, 5, 2, 0), oma = c(2, 1, 1, 1))
  
  plot(1,1, type="n", ylim = c(1,2700), xlim = c(0,55),
       xlab = "Time (hr)", ylab = "Venous Blood Concentration (mg/L)")
  
  # Note, simulations are plotted with the background concentration of 3 mg/L in 
  #  venous blood subtracted out
  lines(out2500_2gi$time.hr, out2500_2gi$C_ven-bgd, col = templ.col5.1, lty = templ.lty, lwd = 3)
  lines(out2500_1gi$time.hr, out2500_1gi$C_ven-bgd, col = templ.col5.2, lty = templ.lty, lwd = 3)
  points(dataB5_2500[["Time"]], dataB5_2500[["C_ven"]], pch = 19, col = pub.col)
  lines(simB5_2500[["Time_2gi"]], simB5_2500[["C_ven_2gi"]]-bgd, col = pub.col5.1, lty = pub.lty, lwd = 2)
  lines(simB5_2500[["Time_1gi"]], simB5_2500[["C_ven_1gi"]]-bgd, col = pub.col5.2, lty = "dotdash", lwd = 2)
  
  #legend("topright", legend = c("Published Data", "EPA IRIS Model - 2 GI", "EPA IRIS Model - 1 GI", "Template Version - 2 GI", "Template Version - 1 GI"),
  #       col = c(pub.col, pub.col5.1, pub.col5.2, templ.col5.1, templ.col5.2), 
  #       lty = c(NA, pub.lty, pub.lty, templ.lty, templ.lty), 
  #       pch = c(19, NA, NA, NA, NA), lwd = c(1, 2, 2, 3, 3))
  
  
  # Create Figure B5, panel B from IRIS tox report 
  plot(1,1, type="n", ylim = c(1,100), xlim = c(0,8),
       xlab = "Time (hr)", ylab = "Venous Blood Concentration (mg/L)")
  
  # Note, simulations are plotted with the background concentration of 3 mg/L in 
  #  venous blood subtracted out
  lines(out100_2gi$time.hr, out100_2gi$C_ven-bgd, col = templ.col5.1, lty = templ.lty, lwd = 3)
  lines(out100_1gi$time.hr, out100_1gi$C_ven-bgd, col = templ.col5.2, lty = templ.lty, lwd = 3)
  points(dataB5_100[["Time"]], dataB5_100[["C_ven"]], pch = 19, col = pub.col)
  lines(simB5_100[["Time_2gi"]], simB5_100[["C_ven_2gi"]]-bgd, col = pub.col5.1, lty = pub.lty, lwd = 2)
  lines(simB5_100[["Time_1gi"]], simB5_100[["C_ven_1gi"]]-bgd, col = pub.col5.2, lty = "dotdash", lwd = 2)
  
  par(mfrow = c(1,1), oma = c(0, 0, 1, 0), mar = c(0, 0, 0, 0), new = TRUE)
  plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
  
  legend("bottomleft", xpd = TRUE, inset = c(0.2, -0.035), bty = "n",
         legend = c("Published Data", "EPA IRIS Model - 2 GI", "EPA IRIS Model - 1 GI"),
         col = c(pub.col, pub.col5.1, pub.col5.2),
         lty = c(NA, pub.lty, "dotdash"), 
         pch = c(19, NA, NA), lwd = c(1, 2, 2))#, text.width = textwidths)
  legend("bottomright", xpd = TRUE, inset = c(0.05, -0.01), bty = "n",
         legend = c("Template Version - 2 GI", "Template Version - 1 GI"),
         col = c(templ.col5.1, templ.col5.2), 
         lty = c(templ.lty, templ.lty), 
         pch = c(NA, NA), lwd = c(3, 3))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
  # Create just high dose figure
  if (!is.null(img.name)){
    sub.img.name <- paste(img.name, "_high.tiff", sep = "")
    tiff(sub.img.name, res=300, height=5, width=6, units="in")
  }
  
  par(old.par)
  
  plot(1,1, type="n", ylim = c(1,2700), xlim = c(0,55),
       xlab = "Time (hr)", ylab = "Venous Blood Concentration (mg/L)")
  
  # Note, simulations are plotted with the background concentration of 3 mg/L in 
  #  venous blood subtracted out
  lines(out2500_2gi$time.hr, out2500_2gi$C_ven-bgd, col = templ.col5.1, lty = templ.lty, lwd = 3)
  lines(out2500_1gi$time.hr, out2500_1gi$C_ven-bgd, col = templ.col5.2, lty = templ.lty, lwd = 3)
  points(dataB5_2500[["Time"]], dataB5_2500[["C_ven"]], pch = 19, col = pub.col)
  lines(simB5_2500[["Time_2gi"]], simB5_2500[["C_ven_2gi"]]-bgd, col = pub.col5.1, lty = pub.lty, lwd = 2)
  lines(simB5_2500[["Time_1gi"]], simB5_2500[["C_ven_1gi"]]-bgd, col = pub.col5.2, lty = "dotdash", lwd = 2)
  
  legend("topright", legend = c("Published Data", "EPA IRIS Model - 2 GI", "EPA IRIS Model - 1 GI", "Template Version - 2 GI", "Template Version - 1 GI"),
         col = c(pub.col, pub.col5.1, pub.col5.2, templ.col5.1, templ.col5.2), 
         lty = c(NA, pub.lty, "dotdash", templ.lty, templ.lty), 
         pch = c(19, NA, NA, NA, NA), lwd = c(1, 2, 2, 3, 3))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
  #Create just low dose figure
  if (!is.null(img.name)){
    sub.img.name <- paste(img.name, "_low.tiff", sep = "")
    tiff(sub.img.name, res=300, height=5, width=6, units="in")
  }
  
  par(old.par)
  
  plot(1,1, type="n", ylim = c(1,100), xlim = c(0,8),
       xlab = "Time (hr)", ylab = "Venous Blood Concentration (mg/L)")
  
  # Note, simulations are plotted with the background concentration of 3 mg/L in 
  #  venous blood subtracted out
  lines(out100_2gi$time.hr, out100_2gi$C_ven-bgd, col = templ.col5.1, lty = templ.lty, lwd = 3)
  lines(out100_1gi$time.hr, out100_1gi$C_ven-bgd, col = templ.col5.2, lty = templ.lty, lwd = 3)
  points(dataB5_100[["Time"]], dataB5_100[["C_ven"]], pch = 19, col = pub.col)
  lines(simB5_100[["Time_2gi"]], simB5_100[["C_ven_2gi"]]-bgd, col = pub.col5.1, lty = pub.lty, lwd = 2)
  lines(simB5_100[["Time_1gi"]], simB5_100[["C_ven_1gi"]]-bgd, col = pub.col5.2, lty = "dotdash", lwd = 2)
  
  legend("topright", legend = c("Published Data", "EPA IRIS Model - 2 GI", "EPA IRIS Model - 1 GI", "Template Version - 2 GI", "Template Version - 1 GI"),
         col = c(pub.col, pub.col5.1, pub.col5.2, templ.col5.1, templ.col5.2), 
         lty = c(NA, pub.lty, "dotdash", templ.lty, templ.lty), 
         pch = c(19, NA, NA, NA, NA), lwd = c(1, 2, 2, 3, 3))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
  
}

methanol.IRIS.FigB7 <- function(img.name = NULL){
  # Creates manuscript Figure 6 (urine concentration) 
  # and Figure S-4 (urine, blood, and body concentrations)
  #
  # Simulates humans exposed to methanol via inhalation for 8 hours at multiple 
  # concentrations. Simulation run for 24 hours.
  
  # Import data and IRIS simulations
  dataB7_231 = read.csv(file = "Data/Data_Methanol/Sedv231.csv", header = FALSE)
  names(dataB7_231) <- c("Time", "C_urine_wbg", "A_urine_wbg")
  dataB7_157 = read.csv(file = "Data/Data_Methanol/Sedv157.csv", header = FALSE)
  names(dataB7_157) <- c("Time", "C_urine_wbg", "A_urine_wbg")
  dataB7_78 = read.csv(file = "Data/Data_Methanol/Sedv78.csv", header = FALSE)
  names(dataB7_78) <- c("Time", "C_urine_wbg", "A_urine_wbg")
  
  simB7_231 <- read.csv(file = "Data/Data_Methanol/FigB7.csv", header = FALSE)
  names(simB7_231) <- c("Time", "C_urine", "C_ven", "C_rb")
  simB8_conc <- read.csv(file = "Data/Data_Methanol/FigB8conc.csv", header = FALSE)
  names(simB8_conc) <- c("Time", "C_urine_231", "Time2", "C_urine_157", "Time3", "C_urine_78")
  simB8_tot <- read.csv(file = "Data/Data_Methanol/FigB8tot.csv", header = FALSE)
  names(simB8_tot) <- c("Time", "A_urine_231", "Time2", "A_urine_157", "Time3", "A_urine_78")
  
  
  # Run simulations
  sim.time <- c(simB8_conc[["Time"]])
  out231 <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                     model.param.sheetname = "IRIS_model_human",
                     exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                     exposure.param.sheetname = "Sedivec_inh_231ppm",
                     data.times = sim.time)
  
  out157 <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                     model.param.sheetname = "IRIS_model_human",
                     exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                     exposure.param.sheetname = "Sedivec_inh_157ppm",
                     data.times = sim.time)
  
  out78 <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                    model.param.sheetname = "IRIS_model_human",
                    exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                    exposure.param.sheetname = "Sedivec_inh_78ppm",
                    data.times = sim.time)
  
  # Calculate error - percent difference between template and IRIS sims
  #ntimes = length(simB8_conc[["Time"]])
  err231 = max(abs(perc.diff(model = out231$R_urine/(70*0.5e-3), 
                             data = simB8_conc[["C_urine_231"]])))
  print(paste0("Max. percent difference for 231 ppm: ", err231))
  
  err157 = max(abs(perc.diff(model = out157$R_urine/(70*0.5e-3), 
                             data = simB8_conc[["C_urine_157"]])))
  print(paste0("Max. percent difference for 157 ppm: ", err157))
  
  err78 = max(abs(perc.diff(model = out78$R_urine/(70*0.5e-3), 
                             data = simB8_conc[["C_urine_78"]])))
  print(paste0("Max. percent difference for 78 ppm: ", err78))
  
  
  # Figure B7
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=6, width=6, units="in")
  }
  
  # Put extra space in the margins to the right of the plot
  old.par <- par(no.readonly = TRUE)
  par(mfrow=c(2, 1), mar=c(4, 4, 1, 19) + 0.1)
  
  #First axes - urine concentrations
  plot(NULL, type="n", xlim = c(0,24), xlab = "Time (hr)",
     ylim = c(0,10), ylab = "Urine Concentration (mg/L)")
  
  lines(out231$time.hr, out231$R_urine/(70*0.5e-3), col = templ.col7.1, lty = templ.lty, lwd = 3)
  lines(simB7_231[["Time"]], simB7_231[["C_urine"]], col = pub.col7.1, lty = pub.lty, lwd = 2)
  points(dataB7_231[["Time"]], dataB7_231[["C_urine_wbg"]], pch = 19, col = pub.col)
  
  #Second axes on same plot - tissue concentrations
  par(new = TRUE)
  plot(NULL, type="n", axes = FALSE, xlim = c(0,24), ylim = c(0,7.7), xlab = "", ylab = "")
  axis(4, ylim=c(0,7.7), col="black",col.axis="black",las=1)
  mtext("Tissue Concentration (mg/L)",side=4,col="black",line=3) 
  
  lines(out231$time.hr, out231$C_ven, col = templ.col7.2, lty = templ.lty, lwd = 3)
  lines(out231$time.hr, out231$C_rb, col = templ.col7.3, lty = templ.lty, lwd = 3)
  lines(simB7_231[["Time"]], simB7_231[["C_ven"]], col = pub.col7.2, lty = pub.lty, lwd = 2)
  lines(simB7_231[["Time"]], simB7_231[["C_rb"]], col = pub.col7.3, lty = pub.lty, lwd = 2)
  
  # # Figure B8 - upper panel
  # par(old.par)
  plot(NULL, type="n", xlim = c(0,24), xlab = "Time (hr)",
      ylim = c(0,10), ylab = "Urine Concentration (mg/L)")
  
  lines(out231$time.hr, out231$R_urine/(70*0.5e-3), col = templ.col7.1, lwd = 3)
  lines(simB8_conc[["Time"]], simB8_conc[["C_urine_231"]], col = pub.col7.1, lty = pub.lty, lwd = 2)
  points(dataB7_231[["Time"]], dataB7_231[["C_urine_wbg"]], pch = 19, col = pub.col7.1)

  lines(out157$time.hr, out157$R_urine/(70*0.5e-3), col = templ.col7.2, lwd = 3)
  lines(simB8_conc[["Time"]], simB8_conc[["C_urine_157"]], col = pub.col7.2, lty = pub.lty, lwd = 2)
  points(dataB7_157[["Time"]], dataB7_157[["C_urine_wbg"]], pch = 19, col = pub.col7.2)

  lines(out78$time.hr, out78$R_urine/(70*0.5e-3), col = templ.col7.3, lwd = 3)
  lines(simB8_conc[["Time"]], simB8_conc[["C_urine_78"]], col = pub.col7.3, lty = pub.lty, lwd = 2)
  points(dataB7_78[["Time"]], dataB7_78[["C_urine_wbg"]], pch = 19, col = pub.col7.3)

  # Add legends for both plots
  par(mfrow = c(1,1), oma = c(0, 0, 0, 2), mar = c(0, 0, 0, 0), new = TRUE)
  plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")

  # Legend for top plot
  legend("topright", xpd = TRUE, inset = c(-0.0, 0.05), bty = "n",
         legend = c("Published Urine Data", "EPA IRIS Model - Urine", "EPA IRIS Model - Blood", "EPA IRIS Model - Body", 
                    "Template Version - Urine", "Template Version - Blood", "Template Version - Body"),
         col = c(pub.col, pub.col7.1, pub.col7.2, pub.col7.3, templ.col7.1, templ.col7.2, templ.col7.3), 
         lty = c(NA, pub.lty, pub.lty, pub.lty, templ.lty, templ.lty, templ.lty),
         lwd = c(1, 2, 2, 2, 3, 3, 3), pch = c(19, NA, NA, NA, NA, NA, NA))
  
  # Legend for bottom plot
  legend("bottomright", xpd = TRUE, inset = c(-0.0, 0.175), bty = "n",
         legend = c("Published Urine Data", 
                    "EPA IRIS Model - 231 ppm", "EPA IRIS Model - 157 ppm",
                    "EPA IRIS Model - 78 ppm", "Template Version - 231 ppm",
                    "Template Version - 157 ppm", "Template Version - 78 ppm"),
         col = c(pub.col, pub.col7.1, pub.col7.2, pub.col7.3,
                 templ.col7.1, templ.col7.2, templ.col7.3),
         lty = c(NA, pub.lty, pub.lty, pub.lty, templ.lty, templ.lty, templ.lty),
         lwd = c(1, 2, 2, 2, 3, 3, 3), pch = c(19, NA, NA, NA, NA, NA, NA))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
  #Create just B-7
  if (!is.null(img.name)){
    sub.img.name <- paste(img.name, "_all.tiff", sep = "")
    tiff(sub.img.name, res=300, height=5, width=7, units="in")
  }
  
  # Put extra space in the margins to the right of the plot
  par(old.par)
  par(mar=c(4, 5, 3, 5) + 0.1)
  
  #First axes - urine concentrations
  plot(NULL, type="n", xlim = c(0,24), xlab = "Time (hr)",
       ylim = c(0,10), ylab = "Urine Concentration (mg/L)")
  
  lines(out231$time.hr, out231$R_urine/(70*0.5e-3), col = templ.col7.1, lty = templ.lty, lwd = 3)
  lines(simB7_231[["Time"]], simB7_231[["C_urine"]], col = pub.col7.1, lty = pub.lty, lwd = 2)
  points(dataB7_231[["Time"]], dataB7_231[["C_urine_wbg"]], pch = 19, col = pub.col)
  
  #Second axes on same plot - tissue concentrations
  par(new = TRUE)
  plot(NULL, type="n", axes = FALSE, xlim = c(0,24), ylim = c(0,7.7), xlab = "", ylab = "")
  axis(4, ylim=c(0,7.7), col="black",col.axis="black",las=1)
  mtext("Tissue Concentration (mg/L)",side=4,col="black",line=3) 
  
  lines(out231$time.hr, out231$C_ven, col = templ.col7.2, lty = templ.lty, lwd = 3)
  lines(out231$time.hr, out231$C_rb, col = templ.col7.3, lty = templ.lty, lwd = 3)
  lines(simB7_231[["Time"]], simB7_231[["C_ven"]], col = pub.col7.2, lty = pub.lty, lwd = 2)
  lines(simB7_231[["Time"]], simB7_231[["C_rb"]], col = pub.col7.3, lty = pub.lty, lwd = 2)
  
  legend("topright",
         legend = c("Published Urine Data", "EPA IRIS Model - Urine", "EPA IRIS Model - Blood", "EPA IRIS Model - Body", 
                    "Template Version - Urine", "Template Version - Blood", "Template Version - Body"),
         col = c(pub.col, pub.col7.1, pub.col7.2, pub.col7.3, templ.col7.1, templ.col7.2, templ.col7.3), 
         lty = c(NA, pub.lty, pub.lty, pub.lty, templ.lty, templ.lty, templ.lty),
         lwd = c(1, 2, 2, 2, 3, 3, 3), pch = c(19, NA, NA, NA, NA, NA, NA))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
  
  # Create just Figure B8 - upper panel
  par(old.par)
  
  if (!is.null(img.name)){
    sub.img.name <- paste(img.name, "_urine.tiff", sep = "")
    tiff(sub.img.name, res=300, height=5, width=6, units="in")
  }
  
  plot(NULL, type="n", xlim = c(0,24), xlab = "Time (hr)",
       ylim = c(0,10), ylab = "Urine Concentration (mg/L)")
  
  lines(out231$time.hr, out231$R_urine/(70*0.5e-3), col = templ.col, lwd = 3)
  lines(simB8_conc[["Time"]], simB8_conc[["C_urine_231"]], col = pub.col, lty = pub.lty, lwd = 2)
  points(dataB7_231[["Time"]], dataB7_231[["C_urine_wbg"]], pch = 19, col = pub.col)
  
  lines(out157$time.hr, out157$R_urine/(70*0.5e-3), col = templ.col, lwd = 3)
  lines(simB8_conc[["Time"]], simB8_conc[["C_urine_157"]], col = pub.col, lty = pub.lty, lwd = 2)
  points(dataB7_157[["Time"]], dataB7_157[["C_urine_wbg"]], pch = 19, col = pub.col)
  
  lines(out78$time.hr, out78$R_urine/(70*0.5e-3), col = templ.col, lwd = 3)
  lines(simB8_conc[["Time"]], simB8_conc[["C_urine_78"]], col = pub.col, lty = pub.lty, lwd = 2)
  points(dataB7_78[["Time"]], dataB7_78[["C_urine_wbg"]], pch = 19, col = pub.col)
  
  legend("topright",
         legend = c("Published Data", "EPA IRIS Model", "Template Version"),
         col = c(pub.col, pub.col, templ.col),
         lty = c(NA, pub.lty, templ.lty),
         lwd = c(1, 2, 3), pch = c(19, NA, NA))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
  
}

methanol.IRIS.FigB11 <- function(img.name = NULL){
  # Creates manuscript Figure 7
  #
  # Simulates humans exposed via an oral dose
  
  # Import data and IRIS simulations
  data = read.csv(file = "Data/Data_Methanol/Schmutte_88_Fig1.csv", header = FALSE)
  names(data) <- c("Time", "C_ven")
  sim = read.csv(file = "Data/Data_Methanol/Fig_B11_sim.csv", header = FALSE)
  names(sim) <- c("Time", "C_ven")
  
  
  # Run simulation
  out <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                  model.param.sheetname = "IRIS_model_human",
                  exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Schmutte_oral_human",
                  data.times = sim[["Time"]])
  
  
  # Calculate error - percent difference between template and IRIS sims
  err = max(abs(perc.diff(model = out$C_ven, data = sim[["C_ven"]])))
  print(paste0("Max. percent difference: ", err))
  
  # Figure B11
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=5, width=6, units="in")
  }
  
  plot(NULL, type="n", xlim = c(0,1.6), xlab = "Time (hr)",
       ylim = c(0,10), ylab = "Blood Concentration (mg/L)")
  
  lines(out$time.hr, out$C_ven, col = templ.col, lty = templ.lty, lwd = 2)
  lines(sim[["Time"]], sim[["C_ven"]], col = pub.col, lty = pub.lty, lwd = 3)
  points(data[["Time"]], data[["C_ven"]], pch = 19, col = pub.col)
  
  legend("bottomright", 
         legend = c("Published Data", "EPA IRIS Model", "Template Version"),
         col = c(pub.col, pub.col, templ.col), lwd = c(1, 2, 3),
         lty = c(NA, pub.lty, templ.lty), pch = c(19, NA, NA))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
}

methanol.IRIS.FigB13 <- function(img.name = NULL){
  # Creates manuscript Figure 8
  #
  # Simulates humans exposed via an iv dose
  
  # Import data and IRIS simulations
  data = read.csv(file = "Data/Data_Methanol/Haffner_92_Fig1.csv", header = FALSE)
  names(data) <- c("Time", "C_venA")
  C_venB=16.5*exp(-0.325*data[["Time"]])
  C_venC=14.8*exp(-0.406*data[["Time"]])
  C_venD=17.8*exp(-0.475*data[["Time"]])
  sim = read.csv(file = "Data/Data_Methanol/Fig_B13_sim.csv", header = FALSE)
  names(sim) <- c("Time", "C_ven")
  
  
  # Run simulations
  out <- PBPK_run(model.param.filename = "MeOH_template_parameters_Model.xlsx",
                  model.param.sheetname = "IRIS_model_human",
                  exposure.param.filename = "MeOH_template_parameters_Exposure.xlsx", 
                  exposure.param.sheetname = "Haffner_iv_human",
                  data.times = sim[["Time"]])
  
  # Calculate error - percent difference between template and IRIS sims
  err = max(abs(perc.diff(model = out$C_ven, data = sim[["C_ven"]])))
  print(paste0("Max. percent difference: ", err))
  
  # Create Figure B13 from IRIS tox report
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=5, width=6, units="in")
  }
  
  plot(NULL, type="n", xlim = c(0,5), xlab = "Time (hr)",
       ylim = c(1,100), ylab = "Blood Concentration (mg/L)", log = "y")
  
  lines(out$time.hr, out$C_ven, col = templ.col, lty = templ.lty, lwd = 2)
  lines(sim[["Time"]], sim[["C_ven"]], col = pub.col, lty = pub.lty, lwd = 3)
  points(data[["Time"]], data[["C_venA"]], col = pub.col, pch = 1)
  points(data[["Time"]], C_venB, col = pub.col, pch = 0)
  points(data[["Time"]], C_venC, col = pub.col, pch = 5)
  points(data[["Time"]], C_venD, col = pub.col, pch = 2)
  
  legend("topright", 
         legend = c("Published Data A", "Published Data B", "Published Data C", 
                    "Published Data D", "EPA IRIS Model", "Template Version"),
         col = c(pub.col, pub.col, pub.col, pub.col, pub.col, templ.col), 
         lty = c(NA, NA, NA, NA, pub.lty, templ.lty), 
         lwd = c(1, 1, 1, 1, 2, 3), pch = c(1, 0, 5, 2, NA, NA))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
}