# R functions to create figures used in the PFAS PBPK model template manuscript
#  Bernstein, et al. (2021)

plot.Kim <- function(out, out.inc=NULL, chem, sex, dose, img.name=NULL, Pylims=NULL){
  # Saves as a tif with name img.name if option is not NULL.
  # Note, you must include the ".tif" in the image name 
  # Dec 2025: input Pylims was added. This should be a list of the form:
  # Pylims=list(plasma=c(yp1,yp2), liver=c(yl1,yl2), kidney=c(yk1,yk2), urine=c(yu1,yu2)),
  # where each element is c(min, max) for the y axis of the corresponding sub-plot.
    
  # Save some colors from the viridis palette. This vector of color-identification
  # strings was generated by calling the function "viridis" from the package
  # "viridis" with the argument "5"; i.e., "viridis(5)".
  #vcol=c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")
  vcol=c("#482576FF", "#25848EFF", "#7AD151FF") #using viridis(3, begin=0.1, end=0.8)
  vcol=c("#440154FF", "#2A788EFF", "#7AD151FF")
  
  paper.col <- vcol[2]; inc.templ.col <- vcol[1]; cor.templ.col <- vcol[3]
  paper.lty <- "dashed"; inc.templ.lty <- "dotted"; cor.templ.lty <- "solid"
  
  # load data
  if (chem == "PFHxS"){ C.units <- "ng/mL"; C.convert <- 1e3; sim.days <- 14
  } else if (chem == "PFNA"){ C.units <- "ug/mL"; C.convert <- 1; sim.days <- 60
  } else if (chem == "PFDA"){  C.units <- "ug/mL"; C.convert <- 1; sim.days <- 150
  }
  C.ylab <- paste("Conc. of ", chem, " (", C.units, ")", sep="")
  Pdata <- load_PlasmaData(chem=chem, species="rat", sex=sex, dose.type="oral", dose=dose)
  Ldata <- load_LiverData(chem=chem, species="rat", sex=sex, dose.type="oral", dose=dose)
  Kdata <- load_KidneyData(chem=chem, species="rat", sex=sex, dose.type="oral", dose=dose)
  Udata <- load_UrineData(chem=chem, species="rat", sex=sex, dose.type="oral", dose=dose)
  
  if (!is.null(img.name)) tiff(img.name, res=300, height=6, width=7, units="in")
  par(mfrow=c(2, 2), mar=c(3, 3, 0, 0), oma=c(3, 0, 1, 1),  mgp=c(1.5, 0.4, 0))
  
  # Plasma concentration plot
  if (is.null(Pylims)){
      y_min <- min(out$C_bl[out$C_bl > 0]*C.convert, Pdata[,4], Pdata[,2], na.rm=TRUE)
      y_max <- max(out$C_bl*C.convert, Pdata[,4], Pdata[,2], na.rm=TRUE)
       if (chem == "PFHxS") { Pylim <- c(y_min,3.5e5)#y_max)#1.5e5
     } else if (chem == "PFNA") { Pylim <- c(y_min, 50)
      } else if (chem == "PFDA") { Pylim <- c(y_min, 25)
      } else { Pylim <- c(y_min, y_max) }
    } else { Pylim = Pylims$plasma }
  
  plot(Pdata[,1], Pdata[,2], col=paper.col, pch=19, log="y", xlim=c(0,sim.days), 
       xlab="Time (day)", ylab=C.ylab, ylim=Pylim)
  lines(out$time.days, out$C_bl*C.convert, lty=cor.templ.lty, lwd=3, col=cor.templ.col)
  lines(Pdata[,3], Pdata[,4], lty=paper.lty, lwd=2, col=paper.col)
  lines(out.inc$time.days, out.inc$C_bl*C.convert, lty=inc.templ.lty, lwd=3, col=inc.templ.col)
  title("Plasma", line=-1.25)
  
  # Liver concentration plot
  if (is.null(Pylims)){
    y_min <- min(out$C_li[out$C_li > 0]*C.convert, Ldata[,4], Ldata[,2], na.rm=TRUE)
    y_max <- max(out$C_li*C.convert, Ldata[,4], Ldata[,2], na.rm=TRUE)
    Lylim <- c(y_min,y_max)
  } else { Lylim = Pylims$liver }

  plot(Ldata[,1], Ldata[,2], col=paper.col, pch=19, log="y", xlim=c(0,sim.days),
       xlab="Time (day)", ylab=C.ylab, ylim=Lylim)
  lines(out$time.days, out$C_li*C.convert, lty=cor.templ.lty, lwd=3, col=cor.templ.col)
  lines(Ldata[,3], Ldata[,4], lty=paper.lty, lwd=2, col=paper.col)
  lines(out.inc$time.days, out.inc$C_li*C.convert,
        lty=inc.templ.lty, lwd=3, col=inc.templ.col)
  title("Liver", line=-1.25)
  
  # Kidney concentration plot
  if (is.null(Pylims)){
    y_min <- min(out$C_ki[out$C_ki > 0]*C.convert, Kdata[,4], Kdata[,2], na.rm=TRUE)
    y_max <- max(out$C_ki*C.convert, Kdata[,4], Kdata[,2], na.rm=TRUE)
    if (chem == "PFHxS") { Kylim <- c(y_min, 3.5e4)#y_max)1.5e4
      } else if (chem == "PFNA") { Kylim <- c(y_min, 0.75e1)#y_max)
      } else if (chem == "PFDA") { Kylim <- c(y_min, 20)
      } else { Kylim <- c(y_min, y_max) }
    } else { Kylim = Pylims$kidney }
  
  plot(Kdata[,1], Kdata[,2], col=paper.col, pch=19, log="y", xlim=c(0,sim.days), 
       xlab="Time (day)", ylab=C.ylab, ylim=Kylim)
  lines(out$time.days, out$C_ki*C.convert, lty=cor.templ.lty, lwd=3, col=cor.templ.col)
  lines(Kdata[,3], Kdata[,4], lty=paper.lty, lwd=2, col=paper.col)
  lines(out.inc$time.days, out.inc$C_ki*C.convert,
        lty=inc.templ.lty, lwd=3, col=inc.templ.col)
  title("Kidney", line=-1.25)
  
  # Urine amount plot
  if (is.null(Pylims)){
    y_min <- min(out$A_urine[out$A_urine > 0]*1000, Udata[,4], Udata[,2], na.rm=TRUE)
    y_max <- max(out$A_urine*1000, Udata[,4], Udata[,2], na.rm=TRUE)
    if (chem == "PFNA" & sex == "female") { Uylim <- c(y_min,400)
    } else {  Uylim <- c(y_min, y_max) }
  } else { Uylim = Pylims$urine }

  plot(Udata[,1], Udata[,2], col=paper.col, pch=19, xlab="Time (day)", ylim=Uylim,
       xlim=c(0,sim.days), ylab=paste("Cum. Amt. of", chem, "(ug)",sep=" "))
  lines(out$time.days, out$A_urine*1000, lty=cor.templ.lty, lwd=3, col=cor.templ.col)
  lines(Udata[,3], Udata[,4], lty=paper.lty, lwd=2, col=paper.col)
  lines(out.inc$time.days, out.inc$A_urine*1000,
        lty=inc.templ.lty, lwd=3, col=inc.templ.col)
  title("Urine", line=-1.25)
  
  par(mfrow=c(1,1), oma=c(0, 0, 0, 0), mar=c(0, 0, 0, 0), new=TRUE)
  plot(0, 0, type="n", bty="n", xaxt="n", yaxt="n")
  
  legend("bottomleft", legend=c("Published Data", "Published Model"),
         xpd=TRUE, inset=c(0.12, 0), bty="n", col=c(paper.col, paper.col),
         lty=c(NA, paper.lty), pch=c(19,NA), lwd=c(1,2))
  legend("bottomright", legend=c("Template Version with Published Flow", 
                                 "Template Version with Corrected Flow"),
         xpd=TRUE, inset=c(0.03, 0), bty="n", col=c(inc.templ.col, cor.templ.col),
         lty=c(inc.templ.lty, cor.templ.lty), pch=c(NA,NA), lwd=c(3,3))#, text.width=textwidths)
  
  if (!is.null(img.name)){
  dev.off()
  }
}

plot.Kudo.Loccisano <- function(out, dose=NULL, img.name=NULL){
  # Saves as a tif with name img.name if option is included.
  # Note, you must include the ".tif" in the image name 
  
  # Save some colors from the viridis palette. This vector of color-identification
  # strings was generated by calling the function "viridis" from the package
  # "viridis" with the argument "5"; i.e., "viridis(5)".
  #vcol=c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")
  vcol=c("#482576FF", "#25848EFF", "#7AD151FF") #using viridis(3, begin=0.1, end=0.8)
  vcol=c("#440154FF", "#2A788EFF", "#7AD151FF")
  paper.col <- vcol[2]; inc.templ.col <- vcol[1]; cor.templ.col <- vcol[3]
  paper.lty <- "dashed"; inc.templ.lty <- "dotted"; cor.templ.lty <- "solid"
  data.loc <- "Data/Digitized_Data_PFOA/"
  
  if (dose == "low"){
    plasma <- read.csv(file=paste0(data.loc, "Data_Fig8_Kudo_lowPlasma.csv"), 
                            header=TRUE, sep=",")
    liver <- read.csv(file=paste0(data.loc, "Data_Fig8_Kudo_lowLiver.csv"), 
                           header=TRUE, sep=",")
  } else if (dose == "high"){
    plasma <- read.csv(file=paste0(data.loc, "Data_Fig8_Kudo_highPlasma.csv"), 
                            header=TRUE, sep=",")
    liver <- read.csv(file=paste0(data.loc, "Data_Fig8_Kudo_highLiver.csv"), 
                           header=TRUE, sep=",")
  }
  
  ylabel="Conc. of PFOA (ug/mL)"; xlabel="Time (hours)"
  if (!is.null(img.name)) tiff(img.name, res=300, height=4, width=7, units="in")
  par(mfrow=c(1, 2), mar=c(3, 3, 0, 0), oma=c(2, 0, 1, 1),  mgp=c(1.5, 0.4, 0))
  
  xmax <- max(out$time); ymin <- min(out$C_bl); ymax <- max(out$C_bl)
  plot(plasma[,1],plasma[,2], col=paper.col, pch=19, xlab=xlabel, xlim=c(0,xmax),
       ylab=ylabel, ylim=c(ymin,ymax))
  lines(out$time, out$C_bl, lty=cor.templ.lty, col=cor.templ.col, lwd=3)
  lines(plasma[,3], plasma[,4], lty=paper.lty, col=paper.col, lwd=2)
  title("Plasma", line=-1.25)
  
  y_min <- min(out$C_li[out$C_li > 0], liver[,2], liver[,4], na.rm=TRUE)
  y_max <- max(out$C_li, liver[,2], liver[,4], na.rm=TRUE)
  Lylim <- c(y_min,y_max)
  
  plot(liver[1,1],liver[1,2], col=paper.col, pch=19, xlab=xlabel, xlim=c(0,xmax),
       ylab=ylabel, ylim=Lylim)
  lines(out$time, out$C_li, lty=cor.templ.lty, col=cor.templ.col, lwd=3)
  lines(liver[,3], liver[,4], lty=paper.lty, col=paper.col, lwd=2)
  title("Liver", line=-1.25)
  
  par(mfrow=c(1,1), oma=c(0, 0, 0, 0), mar=c(0, 0, 0, 0), new=TRUE)
  plot(0, 0, type="n", bty="n", xaxt="n", yaxt="n")
  
  legend("bottom", inset=c(0, 0), xpd=TRUE, bty="n", lwd=c(1,2,3), horiz=TRUE, 
         legend=c("Published Data  ", "Published Model   ", "Template Version"),
         col=c(paper.col, paper.col, cor.templ.col), 
         lty=c(NA, paper.lty, cor.templ.lty), pch=c(19,NA,NA))
  
  if (!is.null(img.name)){
    dev.off()
  }
}

plot.Kemper.Loccisano <- function(out, dose.type=NULL, dose=NULL, sex=NULL, img.name=NULL){
  # Saves as a tif with name img.name if option is included.
  # Note, you must include the ".tif" in the image name 
  
  # Save some colors from the viridis palette. This vector of color-identification
  # strings was generated by calling the function "viridis" from the package
  # "viridis" with the argument "5"; i.e., "viridis(5)".
  #vcol=c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")
  
  vcol=c("#482576FF", "#25848EFF", "#7AD151FF") #using viridis(3, begin=0.1, end=0.8)
  vcol=c("#440154FF", "#2A788EFF", "#7AD151FF")
  paper.col <- vcol[2]; inc.templ.col <- vcol[1]; cor.templ.col <- vcol[3]
  paper.lty <- "dashed"; inc.templ.lty <- "dotted"; cor.templ.lty <- "solid"
  
  data.loc <- "Data/Digitized_Data_PFOA/"
  if (dose.type == "iv"){
    if (sex == "male"){
      plasma <- read.csv(file=paste0(data.loc, "Data_Fig9_Kemper_IVdosePlasma.csv"), 
                         header=TRUE, sep=",")
    } else if (sex == "female"){
      plasma <- read.csv(file=paste0(data.loc, "Data_Fig11_Kemper_IVdosePlasma.csv"), 
                         header=TRUE, sep=",")
    }
  } else if (dose.type == "oral"){
    if (dose == 25){
      if (sex == "male"){
        plasma <- read.csv(file=paste0(data.loc, "Data_Fig9_Kemper_OraldosePlasma.csv"), 
                           header=TRUE, sep=",")
        excretion <- read.csv(file=paste0(data.loc, "Data_Fig9_Kemper_OraldoseExcretion.csv"), 
                              header=TRUE, sep=",")
      } else if (sex == "female"){
        plasma <- read.csv(file=paste0(data.loc, "Data_Fig11_Kemper_OraldosePlasma.csv"), 
                           header=TRUE, sep=",")
        excretion <- read.csv(file=paste0(data.loc, "Data_Fig11_Kemper_OraldoseExcretion.csv"), 
                              header=TRUE, sep=",")
      }
    } else if (dose == 5){
      if (sex == "male"){
        plasma <- read.csv(file=paste0(data.loc, "Data_Supp2_Kemper_Oraldose5Plasma.csv"), 
                           header=TRUE, sep=",")
        excretion <- read.csv(file=paste0(data.loc, "Data_Supp2_Kemper_Oraldose5Excretion.csv"), 
                              header=TRUE, sep=",")
      } else if (sex == "female"){
        plasma <- read.csv(file=paste0(data.loc, "Data_Supp4_Kemper_Oraldose5Plasma.csv"), 
                           header=TRUE, sep=",")
        excretion <- read.csv(file=paste0(data.loc, "Data_Supp4_Kemper_Oraldose5Excretion.csv"), 
                              header=TRUE, sep=",")
      }
    } else if (dose == 1){
      if (sex == "male"){
        plasma <- read.csv(file=paste0(data.loc, "Data_Supp2_Kemper_Oraldose1Plasma.csv"), 
                           header=TRUE, sep=",")
        excretion <- read.csv(file=paste0(data.loc, "Data_Supp2_Kemper_Oraldose1Excretion.csv"), 
                              header=TRUE, sep=",")
      } else if (sex == "female"){
        plasma <- read.csv(file=paste0(data.loc, "Data_Supp4_Kemper_Oraldose1Plasma.csv"), 
                           header=TRUE, sep=",")
        excretion <- read.csv(file=paste0(data.loc, "Data_Supp4_Kemper_Oraldose1Excretion.csv"), 
                              header=TRUE, sep=",")
      }
    }
  }
  
  ylabel="Conc. of PFOA (ug/mL)"; xlabel="Time (hours)"
  
  if (!is.null(img.name))  tiff(img.name, res=300, height=4, width=7, units="in")
  par(mfrow=c(1, 2), mar=c(3, 3, 0, 0), oma=c(2, 0, 1, 1),  mgp=c(1.5, 0.4, 0))
  xmax <- max(plasma[,1])
  y_min <- min(out$C_bl[out$C_bl > 0], plasma[,2], na.rm=TRUE)
  plasmaMax <- max(plasma[,2], plasma[,4], plasma[,6], plasma[,8])
  y_max <- max(out$C_bl, plasmaMax, na.rm=TRUE)
  Pylim <- c(y_min, 200)#y_max)
  
  plot(plasma[,3],plasma[,4], pch=19, col=paper.col, xlab=xlabel, xlim=c(0,xmax),
       ylab=ylabel, ylim=Pylim, log="y")
  points(plasma[,5],plasma[,6], pch=19, col=paper.col)
  points(plasma[,7],plasma[,8], pch=19, col=paper.col)
  lines(plasma[,1], plasma[,2], lty=paper.lty, col=paper.col, lwd=2)
  lines(out$time, out$C_bl, lty=cor.templ.lty, col=cor.templ.col, lwd=3)
  title("Plasma", line=-1.25)
  
  if (dose.type == "oral"){
    urine.percent <- (out$A_urine/(out$A_in[length(out$A_in)]))*100
    feces.percent <- (out$A_fecal/(out$A_in[length(out$A_in)]))*100
    
    y_min <- min(excretion[,2], excretion[,6], na.rm=TRUE)
    y_max <- max(excretion[,2], excretion[,6], na.rm=TRUE)
    Eylim <- c(y_min,75)#y_max)
    
    plot(excretion[,3], excretion[,4], pch=19, col=paper.col, xlab=xlabel,
         xlim=c(0,xmax), ylab="Cum. Percent of Dose", ylim=Eylim, log="y")
    lines(out$time, urine.percent, lty=cor.templ.lty, col=cor.templ.col, lwd=3)
    lines(excretion[,1], excretion[,2], lty=paper.lty, col=paper.col, lwd=2)
    title("Urine", line=-1.25)
    
    lines(out$time, feces.percent, lty=cor.templ.lty, col=cor.templ.col, lwd=3)
    points(excretion[,7], excretion[,8], pch=19, col=paper.col)
    lines(excretion[,5], excretion[,6], lty=paper.lty, col=paper.col, lwd=2)
    title("Feces", line=-7.5)
  }
  
  par(mfrow=c(1,1), oma=c(0, 0, 0, 0), mar=c(0, 0, 0, 0), new=TRUE)
  plot(0, 0, type="n", bty="n", xaxt="n", yaxt="n")
  legend("bottom", inset=c(0, 0), xpd=TRUE, bty="n", lwd=c(1,2,3), horiz=TRUE, 
         legend=c("Published Data  ", "Published Model   ", "Template Version"),
         col=c(paper.col, paper.col, cor.templ.col), 
         lty=c(NA, paper.lty, cor.templ.lty), pch=c(19,NA,NA))
  
  if (!is.null(img.name)) dev.off()
}

# plot Fig 4/6 from Loccisano et al. 2012
plot.3M.Loccisano <- function(out, sex="male", img.name=NULL){
  # Saves as a tif with name img.name if option is included.
  # Note, you must include the ".tif" in the image name 
  
  # Save some colors from the viridis palette. This vector of color-identification
  # strings was generated by calling the function "viridis" from the package
  # "viridis" with the argument "5"; i.e., "viridis(5)".
  #vcol=c("#440154FF", "#3B528BFF", "#21908CFF", "#5DC863FF", "#FDE725FF")
  
  vcol=c("#482576FF", "#25848EFF", "#7AD151FF") #using viridis(3, begin=0.1, end=0.8)
  vcol=c("#440154FF", "#2A788EFF", "#7AD151FF")
  
  paper.col <- vcol[2]
  inc.templ.col <- vcol[1]
  cor.templ.col <- vcol[3]
  
  paper.lty <- "dashed"
  inc.templ.lty <- "dotted"
  cor.templ.lty <- "solid"
  
  data.loc <- "Data/Digitized_Data_PFOS/"
  
  if (sex == "male"){
    plasma <- read.csv(file=paste0(data.loc, "Fig4_3M_OralPlasma.csv"), header=TRUE, sep=",")
    liver <- read.csv(file=paste0(data.loc, "Fig4_3M_OralLiver.csv"), header=TRUE, sep=",")
  } else if (sex == "female"){
    plasma <- read.csv(file=paste0(data.loc, "Fig6_3M_OralPlasma.csv"), header=TRUE, sep=",")
    liver <- read.csv(file=paste0(data.loc, "Fig6_3M_OralLiver.csv"), header=TRUE, sep=",")
  }
  
  ylabel="Conc. of PFOS (ug/mL)"
  xlabel="Time (days)"
  
  y_min <- min(out$C_bl[out$C_bl > 0], plasma[,2], na.rm=TRUE)
  y_max <- max(out$C_bl, plasma[,2], na.rm=TRUE)
  Pylim <- c(y_min,y_max)
  
  if (!is.null(img.name)){
    tiff(img.name, res=300, height=4, width=7, units="in")
  }
  
  par(mfrow=c(1, 2), mar=c(5, 5, 1, 0), oma=c(2, 1, 1, 1))#, cex=1.05, cex.main=1.85, cex.lab=1.45, cex.axis=1.35)
  
  xmax <- max(plasma[,1])
  plot(1,1, type="n", xlab=xlabel, xlim=c(0,xmax),
       ylab=ylabel, ylim=Pylim)
  lines(out$time.days, out$C_bl, lty=cor.templ.lty, col=cor.templ.col, lwd=3)
  lines(plasma[,1], plasma[,2], lty=paper.lty, lwd=2, col=paper.col)
  points(plasma[,3],plasma[,4], pch=19, col=paper.col)
  points(plasma[,5],plasma[,6], pch=19, col=paper.col)
  points(plasma[,7],plasma[,8], pch=19, col=paper.col)
  title("Plasma", line=-1.25)
  
  y_min <- min(out$C_li[out$C_li > 0], liver[,2], liver[,4], na.rm=TRUE)
  y_max <- max(out$C_li, liver[,2], liver[,4], na.rm=TRUE)
  Lylim <- c(y_min,y_max)
  
  C_liTotal <- (out$A_li + out$A_lib)/out$V_li
  
  plot(1,1, type="n", xlab=xlabel, xlim=c(0,xmax),
       ylab=ylabel, ylim=Lylim)
  lines(out$time.days, C_liTotal, lty=cor.templ.lty, col=cor.templ.col, lwd=3)
  points(liver[,3],liver[,4], pch=19, col=paper.col)
  lines(liver[,1], liver[,2], lty=paper.lty, col=paper.col, lwd=2)
  title("Liver", line=-1.25)
  
  par(mfrow=c(1,1), oma=c(0, 0, 0, 0), mar=c(0, 0, 0, 0), new=TRUE)
  plot(0, 0, type="n", bty="n", xaxt="n", yaxt="n")
  
  legend("bottom", inset=c(0, 0), xpd=TRUE, bty="n", lwd=c(1,2,3), horiz=TRUE, 
         legend=c("Published Data  ", "Published Model   ", "Template Version"),
         col=c(paper.col, paper.col, cor.templ.col), 
         lty=c(NA, paper.lty, cor.templ.lty), pch=c(19,NA,NA))
  
  if (!is.null(img.name)){
    dev.off()
  }
  
}


# Functions to load data digitized from Kim et al. 2018, 2019

load_PlasmaData <- function(chem=NULL, species=NULL, sex=NULL, dose.type=NULL, dose=NULL){
  Data <- NULL
  data.loc <- paste("Data/Digitized_Data_", chem, "/", sep="") #data.location(chem)
  
  if (chem == "PFHxS"){
    if (dose.type == "oral"){
      if (sex == "male" && dose == 10.0) Data <- read.csv(file=paste(data.loc, "Fig7a.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female" && (dose == 1.0 || dose == 4.0)) {
        Data <- read.csv(file=paste(data.loc, "Fig8a.csv", sep=""), header=TRUE, sep=",")
        if (dose == 1.0) data_cols=c(1,2,5,6)
        if (dose == 4.0) data_cols=c(3,4,7,8)
        Data <- Data[,data_cols]
      }
    } else if (dose.type == "iv"){
      if (sex == "male" && dose == 10.0) Data <- read.csv(file=paste(data.loc, "Fig3b.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female" && (dose == 0.5 || dose == 1.0 || dose == 4.0 || dose == 10.0)) {
        Data <- read.csv(file=paste(data.loc, "Fig3a.csv", sep=""), header=TRUE, sep=",")
        if (dose == 10.0) data_cols=c(1,2,3,4)
        if (dose == 4.0) data_cols=c(5,6,7,8)
        if (dose == 1.0) data_cols=c(9,10,11,12)
        if (dose == 0.5) data_cols=c(13,14,15,16)
        Data <- Data[,data_cols]
        # Convert data to ng/mL to match other data in paper
        Data[,2] <- Data[,2]*1e3
        Data[,4] <- Data[,4]*1e3
      }
    }
  }
  if (chem == "PFNA"){
    if (dose.type == "oral" && dose == 3.0){
      Data <- read.csv(file=paste(data.loc, "Fig7a.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,5:8]
    } else if (dose.type == "iv" && dose == 3.0){
      Data <- read.csv(file=paste(data.loc, "Fig3a.csv", sep=""), header=TRUE, sep=",")
      if (sex == "male") Data <- Data[,1:4]
      if (sex == "female") Data <- Data[,5:8]
    } else if (dose.type == "iv" && dose == 1.0){
      Data <- read.csv(file=paste(data.loc, "Fig3a.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,9:12]
    } else if (dose.type == "iv" && dose == 0.5){
      Data <- read.csv(file=paste(data.loc, "Fig3a.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,13:16]
    }
  }
  if (chem == "PFDA"){
    if (dose.type == "oral" && dose == 1.0){
      Data <- read.csv(file=paste(data.loc, "Fig8a.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,5:8]
    } else if (dose.type == "iv" && dose == 1.0){
      Data <- read.csv(file=paste(data.loc, "Fig3c.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,5:8]
    }
  }
  Data
}

load_LiverData <- function(chem=NULL, species=NULL, sex=NULL, dose.type=NULL, dose=NULL){
  Data <- NULL
  data.loc <- paste("Data/Digitized_Data_", chem, "/", sep="") #data.location(chem)
  
  if (chem == "PFHxS"){
    if (dose.type == "oral"){
      if (sex == "male" && dose == 10.0) Data <- read.csv(file=paste(data.loc, "Fig7b.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female" && (dose == 1.0 || dose == 4.0)) {
        Data <- read.csv(file=paste(data.loc, "Fig8b.csv", sep=""), header=TRUE, sep=",")
        if (dose == 1.0) data_cols=c(1,2,5,6)
        if (dose == 4.0) data_cols=c(3,4,7,8)
        Data <- Data[,data_cols]
      }
    }
  }
  if (chem == "PFNA"){
    if (dose.type == "oral" && dose == 3.0){
      Data <- read.csv(file=paste(data.loc, "Fig7c.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,c(5:8)]
    }
  }
  if (chem == "PFDA"){
    if (dose.type == "oral" && dose == 1.0){
      Data <- read.csv(file=paste(data.loc, "Fig8c.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,c(5:8)]
    }
  }
  Data
}

load_KidneyData <- function(chem=NULL, species=NULL, sex=NULL, dose.type=NULL, dose=NULL){
  Data <- NULL
  data.loc <- paste("Data/Digitized_Data_", chem, "/", sep="") #data.location(chem)
  
  if (chem == "PFHxS"){
    if (dose.type == "oral"){
      if (sex == "male" && dose == 10.0) Data <- read.csv(file=paste(data.loc, "Fig7c.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female" && (dose == 1.0 || dose == 4.0)) {
        Data <- read.csv(file=paste(data.loc, "Fig8c.csv", sep=""), header=TRUE, sep=",")
        if (dose == 1.0) data_cols=c(1,2,5,6)
        if (dose == 4.0) data_cols=c(3,4,7,8)
        Data <- Data[,data_cols]
      }
    }
  }
  if (chem == "PFNA"){
    if (dose.type == "oral" && dose == 3.0){
      Data <- read.csv(file=paste(data.loc, "Fig7d.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,c(5:8)]
    }
  }
  if (chem == "PFDA"){
    if (dose.type == "oral" && dose == 1.0){
      Data <- read.csv(file=paste(data.loc, "Fig8d.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,c(5:8)]
    }
  }
  Data
}

load_UrineData <- function(chem=NULL, species=NULL, sex=NULL, dose.type=NULL, dose=NULL){
  Data <- NULL
  data.loc <- paste("Data/Digitized_Data_", chem, "/", sep="") #data.location(chem)
  
  if (chem == "PFHxS"){
    if (dose.type == "oral"){
      if (sex == "male" && dose == 10.0) Data <- read.csv(file=paste(data.loc, "Fig7f.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female" && (dose == 1.0 || dose == 4.0)) {
        Data <- read.csv(file=paste(data.loc, "Fig8f.csv", sep=""), header=TRUE, sep=",")
        if (dose == 1.0) data_cols=c(1,2,5,6)
        if (dose == 4.0) data_cols=c(3,4,7,8)
        Data <- Data[,data_cols]
      }
    }
  }
  if (chem == "PFNA"){
    if (dose.type == "oral" && dose == 3.0){
      Data <- read.csv(file=paste(data.loc, "Fig7b.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,c(5:8)]
    }
  }
  if (chem == "PFDA"){
    if (dose.type == "oral" && dose == 1.0){
      Data <- read.csv(file=paste(data.loc, "Fig8b.csv", sep=""), header=TRUE, sep=",")
      if (sex == "female") Data <- Data[,c(5:8)]
    }
  }
  
  Data
}
